export interface GiveawayItem {
  name: string;
  url: string;
}

export interface StoreGiveaway {
  store: string;
  storeUrl?: string;
  startTime?: string;
  items: GiveawayItem[];
}

export interface Region {
  name: string;
}

export const REGIONS: Region[] = [
  { name: '全部' },
  { name: '台北市' },
  { name: '新北市' },
  { name: '宜蘭縣' },
  { name: '桃園市' },
  { name: '新竹市' },
  { name: '新竹縣' },
  { name: '苗栗縣' },
  { name: '台中市' },
  { name: '彰化縣' },
  { name: '雲林縣' },
  { name: '嘉義市' },
  { name: '台南市' },
  { name: '高雄市' },
  { name: '屏東縣' },
  { name: '花蓮縣' },
  { name: '台東縣' },
  { name: '澎湖縣' },
];

export const GIVEAWAYS: Record<string, StoreGiveaway[]> = {
  台北市: [
    {
      store: 'Funbox 忠孝SOGO店',
      storeUrl: 'https://www.facebook.com/funboxsogo',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/YshEzMr' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/VMkcJYH' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/xeHYbqd' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/Nrn2bfq2' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/8KnCSl8R' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/NTHIx7n' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/XEshJg9' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/Y6247D2' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/ZG7OtJY' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/ZLoi4Dx' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/WiTikvvy' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/ZHQWNVU' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/pKMo7GE' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/RaJClbg' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/T2PRZhP' },
      ],
    },
    {
      store: 'Funbox 信義A8',
      storeUrl: 'https://linevoom.line.me/user/_dfItqTWWpJgcZPNYg_b3_xlBeXDhlwTDTicnfSU',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/ZJfKF22' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/wRz58zo' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/VEQJzC3' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/9WebNwX' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/SKirLcd' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/Phbzbw3' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/VeGdajx' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/TABv3w6X' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/7ukC3qG' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/u6HZ2iu' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/7qZYwKM' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/9HZob3M' },
      ],
    },
    {
      store: 'Funbox 三越站前店',
      storeUrl: 'https://linevoom.line.me/user/_dTQ_Ar8kG3TZeWoB_i2PtLW_TclZiMtldppUzAQ',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/76XiEqu' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/RI51Vx8' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/XvBZKlg' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/nvfdLoZ' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/vgFw1zA' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/njnLUe4' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/zUfJfP0' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/usaDh5J' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/sJiCZwR' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/USeuBL5' },
      ],
    },
    {
      store: 'Funbox 南港潤泰',
      storeUrl: 'https://linevoom.line.me/user/_dSeRV-7dSwPAS21zhFTEZS9TU0cjb1gBLwEML9A',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/VynKNIV' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/oy7Cz9BP' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/RV7ycwV' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/qCHfdSx' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/tW9LP8f' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/tOEJRss' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/QtUquaf' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/7XX2Yib' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/vwq27EK' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/R5EUfii' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/v6shPbD' },
      ],
    },
    {
      store: 'Funbox 台北大巨蛋',
      storeUrl: 'https://www.facebook.com/profile.php?id=61593737335376',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/wqvsxLT' },
        { name: 'BX-08 三合一對戰組', url: 'https://lin.ee/9iFpGe3' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Z76uTqx' },
        { name: 'BX-13 騎士長槍', url: 'https://lin.ee/nELuvK5' },
        { name: 'BX-16 王蛇鞭尾 隨機強化組', url: 'https://lin.ee/ptCQLQP' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/NPVAoDT' },
        { name: 'BX-38 赫燃天鳳', url: 'https://lin.ee/NihaSqZ' },
        { name: 'BX-44 三角強襲', url: 'https://lin.ee/SNrDdIr' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/NZDDHKu' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/sxzKaFm8' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/tY81Zmb' },
        { name: 'UX-13 魔像奇岩', url: 'https://lin.ee/UId25v5' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/7WAq435' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/NUJbrDq' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/vODNwsEd' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/Pmk8iM1' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/phMcmpf' },
        { name: 'CX-02 魔導至尊', url: 'https://lin.ee/QFoBRNE' },
        { name: 'CX-06 極狐九尾 隨機強化組', url: 'https://lin.ee/SLXDCFj' },
        { name: 'CX-08 隨機強化組 Vol.7', url: 'https://lin.ee/p4CCVHI' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/Stzqk8d' },
        { name: 'CX-12 鳳凰閃焰', url: 'https://lin.ee/ZrPNssR' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/YkgXjrm' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/nXF44pS' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/TV9MYTU' },
        { name: 'BXG-22 龍騎士S', url: 'https://lin.ee/tk2dKTd' },
      ],
    },
    {
      store: '來玩聚-北車地下街',
      storeUrl: 'https://linevoom.line.me/user/_dXjo38IGuVk3obdbWWB8DVc86lCei15_6UkRuW8',
      startTime: '抽選時間：2026/09/18 12:00~2026/09/19 19:30',
      items: [],
    },
    {
      store: 'Funbox 天母SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_db3MM1gifrvefmBbBLPWOhPAw0aPUL9K3IvLDTk',
      startTime:
        '抽選開放：2026/09/24 11:00｜購買資格券有效：2026/09/24 11:00~22:00、2026/09/25 11:00~21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/VVb3tBK' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/q0kdNkb' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/SS3Qboh' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/SsLuiRu' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/oy3oCkUC' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/r7vciGu' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/PyrM6qd' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/QyozSVa' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/P5iBjAE' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/nzb0ztO' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/RU9VBdJ' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/tJFVpxf' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/QEkIkNw' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/8bDZaOm' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/6oFBWpJ' },
      ],
    },
    {
      store: 'Funbox 遠百信義A13',
      storeUrl: 'https://linevoom.line.me/user/_dZWTe6za3_22gXVkl46uAq37zC6nwkQQCwZnBoA',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/ZIWynRV' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/p5lJKAT' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/PtYZJxN' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/UE7AqTM' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/SEuq9Rw' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/WZqCvGH' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/y96QeFQ' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/oMVrdfL' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/7x6LL1c' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/R9hcN2Y' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/Pwoh8F2' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/yB5uVtL' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/RjBy0mZ4' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/pBJLgiu' },
      ],
    },
    {
      store: 'Funbox 南港LaLaport',
      storeUrl: 'https://linevoom.line.me/user/_dVgaAWKsM1ofi6bVa7iJV1_zOspCOrdSv0vgXKw',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [],
    },
    {
      store: 'Funbox 美麗華',
      storeUrl: 'https://linevoom.line.me/user/_dS6PecGuAayr8FMQ6NoCcETN1oXZ0zgwun4Uivc',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 天母三越店',
      storeUrl: 'https://line.me/R/ti/p/@237annfd',
      startTime: '抽選時間：2026/09/24(11:00)-2026/09/25(21:00',
      items: [
        {
          name: 'BX-37 雙重極限衝擊戰鬥盤豪華組',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M329ATKTY8W80MN3BKVNYWDQ',
        },
        {
          name: 'CX-00 新世紀福音戰士改造組',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M329DVAPY6XZ62WT0FA9XBCT',
        },
        {
          name: 'UX-03 魔導神杖',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33HDH1XMQ02ZJ473JFSW57D',
        },
        {
          name: 'BX-09 戰鬥陀螺X通行證',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33HG0KTYMXE6EAAH31SNJWB',
        },
        {
          name: 'UX-19 子彈獅鷲',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33HJNKKEDH9G3JCNM3TV0AH',
        },
        {
          name: 'CX-19 鱷魚裂甲',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33JB56A1GEQY11VT3ZTPQXJ',
        },
        {
          name: 'UX-15 鮫鯊狂鱗改造組',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33JKTTPJ0R3BPT9FKC3FZY9',
        },
        {
          name: 'CX-11 帝王威能',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33KHHZBD4EYVD5VDRSF4DDY',
        },
        {
          name: 'UX-20 榮耀武神LF',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33KN8A2VBAH6B3FBVY8Q2TF',
        },
        {
          name: 'CX-16 極限對戰組C',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M33N65YF0DEB1DRXYZ6FXSA8',
        },
        {
          name: 'BXG-04 銀牙烈虎S',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M2MFAJH5Q05WXTW5E5H08ZXQ',
        },
        {
          name: 'CX-13 龍王閃擊',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M2MF50GF24ABV42C59R9MGED',
        },
        {
          name: 'CX-00 迪卡狂怒',
          url: 'https://liff.line.me/1654883387-DxN9w07M/c/01M2MEY0Q6AKKHTKP8W7AYATCG',
        },
      ],
    },
    {
      store: 'Funbox 三越南西店',
      storeUrl: 'https://linevoom.line.me/user/_dXRCeNI62-wxECClrgjwMfi8HnY2ow5Onw6aC1A',
      startTime: '抽選/購買時間 2026/09/18 11:00 - 2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Fun box忠孝SOGO',
      storeUrl: 'https://linevoom.line.me/user/_dZR3EbkBX6ugUrxVH_Qo47n8xYDp-95FYmhlIWM',
      items: [],
    },
  ],
  新北市: [
    {
      store: 'Funbox 汐科遠雄',
      storeUrl: 'https://linevoom.line.me/user/_dXWlFT8AyCrEdtsk_fRRUYuqERc8rWDzx3c6DUA',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/PBOv3SP' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/nbXDpNJ' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/vzqFCK8' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/r0ADPrC' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/YZjpRDq' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/NAp1Yeq' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/rFEfuo7P' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/VbhWBoI' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/7dMyI1s' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/6FOilFy' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/uaLaEk1' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/urzSiM2' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/xrLvWNLf' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/xQ5NB2Q' },
      ],
    },
    {
      store: 'Funbox 板橋遠百中山店',
      storeUrl: 'https://linevoom.line.me/user/_dUcATZnmDAam7Low6HB0-JXZC1DzUJEbh8hA8Gg',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/VcXFtoV' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/oEJGoh9' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/X8sxw4V' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/v6Yx0W2' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/pDoTf34' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/V7muDoD' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/zYH5Tbw' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/OSxEgYb' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/TgPNFwu' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/yGeEtjK' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/yNMoNmi' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/xrnvDX8' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/OCSYCb6' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/QOcZMvt' },
      ],
    },
    {
      store: 'Funbox 中和環球店',
      storeUrl: 'https://linevoom.line.me/user/_dSg6slLn5Zg47l9CPlGC-LezlX4EP3fmltKvQRs',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/u3dIcDP' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/OE9U5Qg' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/TJSJjho' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/qRMLD2w' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/vJiN2dv' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/Zx8F0jO' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/v53C4OE' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/Uo68eoZ' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/6RJEzXOj' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/u1KhsQw' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/579Fp7C' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/t9AdfOl' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/wOUSc8e' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/zsClsW5' },
      ],
    },
    {
      store: 'Funbox 樹林秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dSj7fhnsKdDEm1q2ehrYEJTOyrm4OuI2NFsN3I0',
      startTime: '抽選/販售時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/vXQuxDN' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/84qAerv' },
        { name: 'BX-30 X發射器改造型握把（黑紅）', url: 'https://lin.ee/YgfGgzE' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/ngjUBSm' },
        { name: 'BX-41 X發射器改造型握把（黑/透紅）', url: 'https://lin.ee/YnyEe1s' },
        { name: 'BX-42 X發射器改造型握把（藍/透明）', url: 'https://lin.ee/5mPIi2b' },
        { name: 'BX-47 左迴旋風發射器（紅）', url: 'https://lin.ee/XqGvNSc' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/vbgQZUR' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/oAABcl3' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/XGiGWCF' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/TBAna6V' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/YPnrRk1' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/TbKAVfH' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/t3llyXX' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/Nm2NSQE' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/TChapUa' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/SeIuM1N' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/xBMpnkL' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/yncSVMg' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/VErVVSy' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/vjx3zpC' },
      ],
    },
    {
      store: 'Funbox 板橋大遠百',
      storeUrl: 'https://linevoom.line.me/user/_dblyPGfsKpebVOKvBaP8gs72hysvg-G0EVYLyv4',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/7IrVvjjs' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/5GpJ4Ai' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/6lOvA7Y' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/R9jSp7d' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/wWNx0DB' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/onLU7z8' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/worKtlI' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/7g2a6vt' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/RqJGeij' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/Szv66C8' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/WRBEjBM' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/YXFR5Um' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/WNs3mNZ' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/UjbSTmh' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/vuMIKiU' },
      ],
    },
    {
      store: 'FUNBOX 比漾廣場店',
      storeUrl: 'https://linevoom.line.me/user/_dQbxr4jKpXDT3BtXULflBCgU9GujoUvNaAUOOZo',
      startTime: '抽選/購買時間 2026/09/18 開店 - 2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 新店誠品-裕隆城',
      startTime:
        '抽選：2026/09/24 11:00 開放｜購買資格券有效：2026/09/24 11:00~21:30、2026/09/25 11:00~21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/7TK6Kqw' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/qlrFB7z' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/7otdg5h' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/uCKAJ6S' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/P1qNYyV' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/75H4hw2' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/WJ6E5Uu' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/N5lTSUH' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/uKOxRt7' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/z3ExN0d' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/nDiqthy' },
      ],
    },
  ],
  宜蘭縣: [
    {
      store: 'Funbox 宜蘭新月店',
      storeUrl: 'https://line.me/R/ti/p/@027iendl',
      startTime:
        '抽選開放：2026/09/24 11:00｜購買資格券有效：2026/09/24 11:00~22:00、2026/09/25 11:00~21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/8j7pVr3y' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/9L5Ff5b' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/zA0DUXh' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/6zkYNmw' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/yIeuoJw' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/uvcDoB5' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/rkkJbfy' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/URnAGAi' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/Niehpsa' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/u8s8Df5' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/PYDqR8A' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/9VsouRx' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/UuG58MV' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/NXmk14K' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/x1NjjPn' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/y4rpdZj' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/S57VxgE' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/YEyrUCi' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/ZksZugs' },
      ],
    },
  ],
  桃園市: [
    {
      store: 'Funbox 桃園新光站前店',
      storeUrl: 'https://www.facebook.com/share/p/1BwVdTcFYL/?mibextid=wwXIfr',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/pAfl4Sp' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/v5uMKHD' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/nxwYe6U' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/vXOPypA' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/7hZVM1E' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/Pzm9qB8' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/64u8OUS' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/YOnDqu8' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/57xH5R8' },
      ],
    },
    {
      store: 'Funbox 桃園環球A8',
      storeUrl: 'https://lin.ee/sWtYTIo',
      startTime: '戰鬥陀螺X抽籤及販售時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        {
          name: 'UX-03 魔導神杖',
          url: 'https://lin.ee/tzSxsn6',
        },
        {
          name: 'CX-00 新世紀福音戰士改造組',
          url: 'https://lin.ee/vKF8f0b',
        },
        {
          name: 'UX-19 子彈獅鷲H',
          url: 'https://lin.ee/SyOwr0E',
        },
        {
          name: 'CX-19 鱷魚裂甲',
          url: 'https://lin.ee/uLS7PYx',
        },
        {
          name: 'UX-15 鮫鯊狂鱗改造組',
          url: 'https://lin.ee/Y4P9FVt',
        },
        {
          name: 'BX-09 戰鬥陀螺X通行證',
          url: 'https://lin.ee/UM9BL7I',
        },
        {
          name: 'CX-11 帝王威能',
          url: 'https://lin.ee/rtaY68A',
        },
        {
          name: 'UX-20 榮耀武神LF',
          url: 'https://lin.ee/qms7c7d',
        },
        {
          name: 'UX-14 天蠍長矛0-70Z',
          url: 'https://lin.ee/RCtkQXl',
        },
        {
          name: 'CX-14 騎士堡壘',
          url: 'https://lin.ee/r6zDIpR',
        },
        {
          name: 'CX-01 蒼龍勇氣',
          url: 'https://lin.ee/8kJ56Jz',
        },
        {
          name: 'CX-17 隨機強化組 Vol.10',
          url: 'https://lin.ee/TUEGNnc',
        },
        {
          name: 'CX-16 極限衝擊對戰組C',
          url: 'https://lin.ee/ostwMDV',
        },
        {
          name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組',
          url: 'https://lin.ee/shmluZw',
        },
      ],
    },
    {
      store: 'Funbox Toys 桃園台茂店',
      storeUrl: 'https://lin.ee/RawWy0S',
      startTime: '戰鬥陀螺X抽籤及販售時間：2026/09/24 11:00~2026/09/25 21:30',
      items: [
        {
          name: 'UX-19 子彈獅鷲H',
          url: 'https://lin.ee/O3FAyMl',
        },
        {
          name: 'UX-20 榮耀武神LF',
          url: 'https://lin.ee/YpSZjTy',
        },
        {
          name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組',
          url: 'https://lin.ee/vNkXt6Mb',
        },
        {
          name: 'CX-11 帝王威能',
          url: 'https://lin.ee/uY5FY0a',
        },
        {
          name: 'UX-03 魔導神杖',
          url: 'https://lin.ee/VBb3bnxt',
        },
        {
          name: 'BX-09 戰鬥陀螺X通行證',
          url: 'https://lin.ee/XV9dEnq',
        },
        {
          name: 'CX-19 鱷魚裂甲',
          url: 'https://lin.ee/VHzwlTI',
        },
        {
          name: 'UX-15 鮫鯊狂鱗改造組',
          url: 'https://lin.ee/pRfwiuA',
        },
        {
          name: 'CX-00 新世紀福音戰士改造組',
          url: 'https://lin.ee/9lwyKUG',
        },
        {
          name: 'CX-16 極限衝擊對戰組C',
          url: 'https://lin.ee/8QPj39E',
        },
        {
          name: 'UX-14 天蠍長矛0-70Z',
          url: 'https://lin.ee/nAefLbB',
        },
        {
          name: 'CX-01 蒼龍勇氣',
          url: 'https://lin.ee/yLvhPAC',
        },
        {
          name: 'CX-17 隨機強化組 Vol.10',
          url: 'https://lin.ee/y6VgEZg',
        },
        {
          name: 'CX-14 騎士堡壘',
          url: 'https://lin.ee/72zTcvIh',
        },
      ],
    },
    {
      store: 'Funbox 中壢大江店',
      storeUrl: 'https://linevoom.line.me/user/_daOwg6Nz08TwGFzWoVR264J1CWj5Lp8g0Lgf-QM',
      startTime: '抽選&購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [],
    },
    {
      store: 'Funbox 環球桃園A19',
      storeUrl: 'https://linevoom.line.me/user/_dQguBN50HV7T3jjTaZbJKVwoET6cJJH2Kj43Y2E',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/7PFgK96' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/PvNofBo' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/rZX23vR' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/OgZw6rF' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/p95mSoO' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/PV1A9yi' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/6OStfzH' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/vyUsS03' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/nhkOKkS' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/Yqd9XJV' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/Q9Tg5Xf' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/unrHrX2' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/TtRgfjcD' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/qupdDqV' },
      ],
    },
  ],
  新竹市: [
    {
      store: 'Funbox-新竹遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dYjgWm0vwMyoPEcmLUOBhOQ55A0WaB7EuLfW5Mw',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 新竹巨城店',
      storeUrl: 'https://linevoom.line.me/user/_dSYAGjN3DhBtiB8tU2pa3kl5yoRdBG7ucZNUZvo',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 新竹遠雄',
      storeUrl: 'https://line.me/R/ti/p/@agl4214l',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/UNHRh8N' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/U2XImIs' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/rhXX6Yb' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/QnD08xb' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/X3HxPnrp' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/ViL8jZe' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/PNuw4Ja' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/WOTuVwM' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/tjFdZv1' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/uiQ9EWq' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/wz0Rbbz' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/xalwk8P' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/v4tJqVM' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/WmwYfWUG' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/OI107KT' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/w3hstkV' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/OnL9KLi' },
      ],
    },
  ],
  新竹縣: [
    {
      store: 'Funbox 竹北遠東店',
      storeUrl: 'https://linevoom.line.me/user/_deu1wnG4xXho1I98-nH_PZKQ0gl-iAoehGDIHxA',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/ZmLAL2o' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/7JREme9' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/yBK7Gsl' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/71fMFkZ' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/ukP9eVS' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/Q76QJlO' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/P2DIGzd' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/vamByNQ' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/9Yh2bh8' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/PpljeCnI' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/6jYLz6l' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/PiPpBqA' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/P2l4q9k' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/8iTSfDL' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/p6FcqNa' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/swVbKuJ' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/RFarJwx' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/SS38y60' },
      ],
    },
    {
      store: 'funbox 享平方店',
      storeUrl: 'https://linevoom.line.me/user/_dfuDiJPQBJn4ih1iarevDIEIB9XvR-_q44VI6bE',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19（依原公告）',
      items: [],
    },
  ],
  苗栗縣: [],
  台中市: [
    {
      store: 'Funbox 台中港三井店',
      storeUrl: 'https://linevoom.line.me/user/_dXDniXt3Xu0U5lkXYliBBHGQRD2FtCUnVVbXPhY',
      startTime: '抽籤時間&使用期限：2026/09/24 11:00~2026/09/25 20:30',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Wk3tdkx' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/savT9fS' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/tyxhyv9' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/vITm6q8' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/o8u8ztc' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/54FD9j4' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/WLF39W1' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/zIhTLPo' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/YD4g9U0' },
      ],
    },
    {
      store: 'Funbox 廣三SOGO',
      storeUrl: 'https://linevoom.line.me/user/_dUpKOzSR_s9Wca-q8vJLgOSM-UGMJNMonlEK_Nw',
      startTime: '抽選/販售時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/9Uf7ufK' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/6grPYeL' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/wtbUTAoh' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/RK8ZDxt' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/v3HLIRF' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/QZU2A0i' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/YUGkH3g' },
      ],
    },
    {
      store: 'Funbox 豐原太平洋店',
      storeUrl: 'https://linevoom.line.me/user/_dWUEiTQIz0C550q-X-t3o65-r0CLa8-fBL6b6u8',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/5nzhZft' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/NMVdvD5' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/pFcgAGY' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/74FuRUf' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/N6cmihY' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/tLDf1Dt' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/QwIyino' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/8tkHUiw' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/ZbOoNTl' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/Ty3QSiG' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/5JILYZA' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/S0F2ynl' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/rQ2tigNX' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/qioqjN2' },
      ],
    },
    {
      store: 'Funbox 麗寶一期',
      storeUrl: 'https://linevoom.line.me/user/_dZD8OLWoBDH7CMfvg3nqfJoIb3wQMGpZ_V7DOOI',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/7dsc3dT' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/pFTCYU6' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/SPEEd26' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/ps707JS' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/8ZsoTqV' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/VmoY8Uh' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/sozZOpC' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/Q8ygEXU' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/WyVn0sM' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/XIQTy7t' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/t9S4nva' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/RheaST0' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/uWxlJPd' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/QdoraNG' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/nIlHv7g' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/YNBU9jZ' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/Zzq8Yar' },
      ],
    },
    {
      store: 'Funbox 新光三越台中中港店',
      storeUrl: 'https://linevoom.line.me/user/_dcavY93jrqjYaLVO8JR44m7jxZNARF__lfYuyIo',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/OVur9GB' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/W4EJ77n' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/tV9x6Ys' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/710kotD' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/6LtO3ZP' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/p4nlZ8r' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/UXIn80W' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/RrkYa0P' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/TQs0wo0' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/zIfGpDL' },
      ],
    },
    {
      store: 'Funbox 台中中友',
      storeUrl: 'https://linevoom.line.me/user/_dVExgXo7x7ugfZBDIYzfRF8XR9geWiZncXXAkNM',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Rqg0ci6' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/wUnWMbf' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/pg9j4Rw' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/QTVg5GZ' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/6cbE2E5' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/q0Ld8D9' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/T6JAi7i' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/z5RDqso' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/qOH6Eud' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/uNuEvrE' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/pc7cdNaG' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/VocX7sP' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/wWAwwfM' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/UKSRtOt' },
      ],
    },
    {
      store: 'Funbox 台中新時代店',
      storeUrl: 'https://line.me/R/ti/p/@hdg3289a',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 文心秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dVbUMDyduUeLgyWJWRb0k8o55Sa-xzXFMnCJxpE',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
  ],
  彰化縣: [
    {
      store: '來玩聚 彰化店',
      storeUrl: 'https://linevoom.line.me/user/_deL1i2Bb8uUCbeQ10yCnEvVLz_iZbXwvFtNNTRM',
      startTime: '抽選/購買時間：2026/09/24 10:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/r60AwuZ' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/tcmkNy1' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/o9UG4Dj' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/nIxO8Fi' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/Z2pj8el' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/w5wHVol' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/Z8eaFgf' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/6Oe8I3R' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/nykRzCt' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/xmka2Np' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/6EETvBIo' },
      ],
    },
    {
      store: '來玩聚 員林店',
      storeUrl: 'https://linevoom.line.me/user/_dar-0z1aYQPkB0W-BiwgwDp6XsDKAdehbmupEaI',
      startTime: '抽選/購買時間：2026/09/24 10:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/un48dpJ' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/TmRL4Vo' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/PNvodgp' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/9UNOMcg' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/sp8XlMJ' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/pw1QBPY' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/rRy4gCo' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/wTX5Y7v' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/OjXiGVT' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/9vZCLEUx' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/uHhFRaP' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/ZAJe0VL' },
      ],
    },
  ],
  雲林縣: [
    {
      store: '來玩聚 斗六店',
      storeUrl: 'https://linevoom.line.me/user/_ddu256ZXwJCBqOeIfKwY6QYdeIvbrVOmBRIOKfo',
      startTime: '抽選/購買時間：2026/09/24 10:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/STkZhA3' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/pbF9fgb' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/ZmanjT2' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/9IC7z0X' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/YLUulgy' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/qR1Ryrl' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/VYaVdjE' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/PvSXvcq' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/7qyeQfM' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/n50i3Qx' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/tV4vYiw' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/8NKapCX' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/UIJHH23' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/67jouS2' },
      ],
    },
  ],
  嘉義市: [
    {
      store: 'Funbox 嘉義遠東',
      storeUrl: 'https://linevoom.line.me/user/_dVzi6SpAv9EDTDhGlf38KyYzGRC3R0O0O6zxlno',
      startTime:
        '抽選資格：2026/09/24 11:00~2026/09/25 20:30｜中籤購買：9/24 11:00~21:30、9/25 11:00~20:30',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/VV2H8LQ' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/pJH7eAO5' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/VXvirDW' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/sdDdb39' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/ZNRSgFT' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/xbSWUFv' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/6haPXQw' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/ua3jxQT' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/vOyPw48' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/ngKmrjRA' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/79GQVHt' },
      ],
    },
    {
      store: 'Funbox 嘉義耐斯',
      storeUrl: 'https://line.me/R/ti/p/@121vsdww',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 嘉義三越',
      storeUrl: 'https://linevoom.line.me/user/_dVZ_jIBO92xnDLzsC9JfjVWMgA2TNLQ2hncb3Ok',
      startTime:
        '抽選開放：2026/09/24 11:00｜購買資格券有效：2026/09/24 11:00~22:00、2026/09/25 11:00~21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/uIMdTNA' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/ZIIQ7Tu' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/8b2IV4s' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/R9ryviu' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/wQTBi7s' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/xbg4NYc' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/8b2ZEa1' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/YnZm5Gc' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/uKjhZZs' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/9cliiv2' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/x9wv2f9k' },
      ],
    },
  ],
  台南市: [
    {
      store: 'Funbox 台南遠百店',
      storeUrl: 'https://linevoom.line.me/user/_dWKgSOpFJ9bwQuysxkGH0jnCsb22vMfW7kuZDzU',
      startTime: '抽選/購買資格時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/7HHtuxJ' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/WsCiWcE' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/7IQtQud' },
      ],
    },
    {
      store: 'Funbox 台南三井',
      storeUrl: 'https://linevoom.line.me/user/_dTp06Slhdio7LDmd8xKxz3J2mw25-ZMRXZtXQ9I',
      startTime: '抽選/購買資格時間：2026/09/24 11:00~2026/09/25 20:30',
      items: [
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/7aUiQZj' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/R23fMiR' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/rMs6Eje' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/s1q7RXD' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/7B3N5c2' },
      ],
    },
    {
      store: 'Funbox 台南南紡店',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Pli4xNZ' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/6GyezJBZ' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/NxXyVCN' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/TG9sizn' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/WYcyP75' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/qHdUxaI' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/NKIO9MI' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/wOkTyc2' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/yHPadq6' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/PEMGo03' },
      ],
    },
    {
      store: '來玩聚 新仁店',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 20:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/zgKROZn' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/XvVP7KD' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/r16D4bQ' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/ODgkW5R' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/pOUNMVw' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/5eP2Pw3' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/VE21rrw' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/ZumYov4' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/nKd8pzE' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/nWGXbfC' },
      ],
    },
    {
      store: 'Funbox 台南新天地',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/8WiozWW' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/rzQi05Z' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/W8QuMRr' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/68VnVGF' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/t1mTxrj' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/8RIFn21' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/rYfPCN0' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/nIEyqYK' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/q5s7t9pV' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/WHMekkc' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/7a6Bd2T' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/yb6m4X2' },
      ],
    },
  ],
  高雄市: [
    {
      store: '鳳山來玩聚',
      storeUrl: 'https://linevoom.line.me/user/_dYHKZsEifm4hbpeUB6f8DAHE-NaYM-f4lmS_yxc',
      startTime: '戰鬥陀螺X抽籤及販售時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/odidkRY' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/Ojm7sbC' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/xP1iIML' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/W6kvdA0' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/z0lIOr5' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/yt0clFc' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/xCiXOPE' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/qzlscme' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/QqwJr83' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/VzoegrJ' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/63sP76g' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/zycDkjs' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/UnKwPJW' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/yPsPcu70' },
      ],
    },
    {
      store: 'Funbox 高雄SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_dV2_iZGnvicFJijn62vXHA57ANIeliHDGI7gnRo',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/YAylEJJ' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/8z1Cmww' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/qOabwSM' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/RRRHxf8' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/WI9iwCc' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/V3zucKg' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/SBoWBrL' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/umKu0I8' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/OHl23Fv' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/XOxNifL' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/QI2NcAVK' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/ZRrT2Kn' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/qKQdCDY' },
      ],
    },
    {
      store: 'Funbox 高雄大立店',
      storeUrl: 'https://linevoom.line.me/user/_dQjEieF9ohNmyCT1yYbOpfT_jw3DHpatmfmuM5o',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 20:30',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Zu2jSm5' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/yErYbDn' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/sb9nmJ2' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/5viKYYX' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/zQsErXs' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/osOVx4c' },
      ],
    },
    {
      store: 'Funbox 夢時代店',
      storeUrl: 'https://linevoom.line.me/user/_dVHpcOhwVrBQ3ZY1xQBHuGMcluZ-yMcOSsSnRfU',
      startTime: '抽選/購買時間：2026/09/24 10:30~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/yUB8qSDB' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/ppqAPWc' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/6IwEG9j' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/8D4vxFV' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/yfg15d0' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/qmMR6qj' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/oogIRh9' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/6rxbmWE' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/Tp4x0BeF' },
      ],
    },
    {
      store: 'Funbox 高雄漢神店',
      storeUrl: 'https://linevoom.line.me/user/_dZFySf-_Iy1JFk7B9OJx3p-R8KIqsjXVk6wMx_s',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/X8yrlXR' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/UOEv6hR' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/sAjO21Y' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/xtdDJkR' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/PT4065u' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/rQfpqpg' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/Yi1VATa' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/tG3B1r4' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/7J1nRKb' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/x3NiEvE' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/5V60I72' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/7CakQ0g' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/9QWuh4M' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/QtVz2AF' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/ZUXl1gU' },
      ],
    },
    {
      store: 'Funbox 漢神巨蛋店',
      storeUrl: 'https://linevoom.line.me/user/_dZuBlwRH9v-DXFkhIH9m1xAU7En6xl4R3qc363s',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Scneenz' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/n8iaDUd' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/pdXmXfxb' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/vyqcdR9' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/5BVkCpc' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/PP7G1hro' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/PzqGL8g' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/7BvSNKA' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/nLlHxdq' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/vSmSoBP' },
      ],
    },
    {
      store: 'Funbox 大魯閣新光',
      storeUrl: 'https://linevoom.line.me/user/_dQ0ecVMFJ6V-NPSlxQbE5hqjsBH-WOBO5HdSv4Q',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/n2FXZ39' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/zmTDdxN' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/Yb8DjfX' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/SrBM6Mc' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/5vzfUUj' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/ZVLuzhb' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/zsP8kQU' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/7I9zWIv' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/vevpwWq' },
      ],
    },
    {
      store: 'Funbox 高雄大遠百',
      storeUrl: 'https://linevoom.line.me/user/_dYOR2VczscGNCah5bglUoA62Gj_YR_lq2R-UoMs',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/qmgJ5cF' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/UFPNQlD' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/SWf2Qr3' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/vXMZd9V' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/oY1fqxT' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/OoNyFK6' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/QTr3rPy' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/NmZMwQS' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/uol2ZFz' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/XOuvbgOV' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/NnWA6oL' },
      ],
    },
    {
      store: '來玩聚 楠梓店',
      storeUrl: 'https://linevoom.line.me/user/_dVPoSlHQT0aqmC-EZpckQXYHAMiL802BM23S7qk',
      startTime: '抽選/購買時間：2026/09/24 10:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/NRcKg4oO' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/yb0OYpE' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/6rMo38F' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/sTKEOby' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/xUr19ui' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/sfBM9IS' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/NIDfJkp' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/XBGmEgK' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/z1t2sUz' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/tRVMZyr' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/vsBuoVD' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/WU0eqw6' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/z1WQMja' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/X6qvU1j' },
      ],
    },
    {
      store: 'Funbox 高雄左營店',
      storeUrl: 'https://line.me/R/ti/p/@obz8096L',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 義大2館',
      storeUrl: 'https://line.me/R/ti/p/@bxd6822t',
      startTime: '抽選時間：2026/09/18 11:00~2026/09/19 21:00',
      items: [],
    },
    {
      store: 'Funbox 高雄義享店',
      storeUrl: 'https://line.me/R/ti/p/@777nkbeo',
      startTime: '抽選/購買時間：2026/09/24 10:30~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/VVu20RW' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/SJcw1NV' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/xk1ROiD' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/X601X11N' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/QlOShbH' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/OyY3oj8' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/o22kXk6' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/rY5sM6Pg' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/N0LCLLa' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/WKOcpt8P' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/Wbg5gBn' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/Ri7uGke2' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/RMMdRKV' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/z3yymC5' },
      ],
    },
    {
      store: '來玩聚 新楠店',
      storeUrl: 'https://linevoom.line.me/user/_deAwpKm1kymi62-wvUqTCvK1LpCSk5bvwxAubMQ',
      startTime: '抽選/購買時間：2026/09/24 10:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/Qjs97Zl' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/OTfmwRL' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/Sb8wo4R' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/YgPEy2f' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/R6RNEnN' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/PaaGBOJ' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/tsJ67g2' },
      ],
    },
  ],
  屏東縣: [
    {
      store: 'Funbox 屏東太平洋店',
      storeUrl: 'https://linevoom.line.me/user/_dTnMNq0eoiZ5jnuQaFUz2oVpxylrT13ojfI_Ko8',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/sIAraz3' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/W00QvT8' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/splMMW0' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/Xs958LQ' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/ptK8LLe' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/ZBXvSX3' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/YQO68w0' },
      ],
    },
    {
      store: 'Funbox 屏東環球',
      storeUrl: 'https://linevoom.line.me/user/_dfq4IRS_qaEaR4Svk0SKsB78xW9x2-lkU1wSpKU',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/nK47qYu' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/xG6uooK' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/qyyGsgD' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/n4AQygz' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/vVunP5H' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/UlLnpDZ' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/PPylghy' },
      ],
    },
  ],
  花蓮縣: [
    {
      store: 'Funbox 花蓮店',
      startTime: '抽選開始：2026/09/24（四）11:00（貼文未註明截止時間）',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/R6VkGMx' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/ptAqGN1' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/9O2jMME' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/wwL4SIJ' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/8to54tw' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/uh52XfdO' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/72OX6Oh' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/Z0iOeRn' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/PioYUuYh' },
      ],
    },
  ],
  台東縣: [
    {
      store: 'Funbox 台東秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dWiMasxT4CrK1ogY11eoxXAVvwO-U9Fchsvba6o',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/rxJTCiK' },
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/xoowkHb' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/8ErDIEU' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/yhVE8IG' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/trxEGg3' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/vqKZpb8' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/Vjh0hul' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/R8q57Ab' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/wbeCA3W' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/PhrpKEC' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/nF0AYIz' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/qZJ0gfH' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/SkVQDaI' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/nLXL0xc' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/nm0zCbs' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/ub3yckW' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/rocQngr' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/vRkFTMl' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/SUAnfa6' },
      ],
    },
    {
      store: '來玩聚 台東家樂福',
      startTime: '抽選/購買時間：2026/09/24 11:00~2026/09/25 20:00',
      items: [
        { name: 'BX-09 戰鬥通行證', url: 'https://lin.ee/t3i5Mlt' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/qeGvOE4' },
        { name: 'UX-14 天蠍長矛', url: 'https://lin.ee/NYUVCT2' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/VVz8hMqX' },
        { name: 'UX-19 子彈獅鷲', url: 'https://lin.ee/nA6CwFe' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/WYa0x43' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/6LfyCqM' },
        { name: 'CX-00 迪卡狂怒 FT3-60T', url: 'https://lin.ee/OJXX1Wb' },
        { name: 'CX-01 蒼龍勇氣', url: 'https://lin.ee/ShNsv6k' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/zi3vmb8' },
        { name: 'CX-14 騎士堡壘', url: 'https://lin.ee/pflIbwY' },
        { name: 'CX-16 極限衝擊對戰組C', url: 'https://lin.ee/R8x168I' },
        { name: 'CX-17 隨機強化組Vol.10', url: 'https://lin.ee/YlJjztC' },
        { name: 'CX-19 鱷魚裂甲', url: 'https://lin.ee/6G1cFJx' },
      ],
    },
  ],
  澎湖縣: [
    {
      store: 'Funbox 澎湖3號港店',
      startTime: '抽選/購買時間：2026/09/24 10:00~2026/09/25 20:30',
      items: [
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/XAGz7XY' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/n5N01Gy' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/9oDCwR5' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/ngmDuez' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/RT4xYnV' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/XTrDxwZ' },
      ],
    },
  ],
};
