export interface GiveawayItem {
  name: string;
  url: string;
}

export interface StoreGiveaway {
  store: string;
  storeUrl?: string;
  startTime?: string;
  items: GiveawayItem[];
}

export interface Region {
  name: string;
}

export const REGIONS: Region[] = [
  { name: '全部' },
  { name: '台北市' },
  { name: '新北市' },
  { name: '桃園市' },
  { name: '新竹市' },
  { name: '新竹縣' },
  { name: '宜蘭縣' },
  { name: '台中市' },
  { name: '嘉義市' },
  { name: '台南市' },
  { name: '高雄市' },
];

export const GIVEAWAYS: Record<string, StoreGiveaway[]> = {
  台北市: [
    {
      store: 'Funbox-忠孝SOGO店',
      storeUrl: 'https://www.facebook.com/funboxsogo',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）21:00',
      items: [
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/xe0367ja' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/xxqkyvC' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/TmhBnu9' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/9xvdY8S' },
        {
          name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組',
          url: 'https://lin.ee/yP3r8Lq',
        },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/tratm8F' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/zrGLkVA' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/QrlSYOm' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/suYW8By' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/XoUgnBE' },
      ],
    },
    {
      store: 'Funbox-LaLaport南港',
      storeUrl: 'https://linevoom.line.me/user/_dVgaAWKsM1ofi6bVa7iJV1_zOspCOrdSv0vgXKw',
      items: [
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/wxDyuiT' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/T4epzhr' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/5S33T6A' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/5OhxHJr' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/okwRin0' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/xCP9NsQ' },
        { name: 'UX-20榮耀武神LF', url: 'https://lin.ee/qHTOOuh' },
        { name: 'UX-19子彈獅鷲H', url: 'https://lin.ee/YeKJb8H' },
        { name: 'UX-11衝擊龍神豪華組', url: 'https://lin.ee/6x5RoXJ' },
        { name: 'UX-03魔導神杖', url: 'https://lin.ee/SKB9Mzm' },
        { name: 'UX-02惡魔戰錘', url: 'https://lin.ee/T0GDMsh' },
        { name: 'BXG-04銀牙獵虎S', url: 'https://lin.ee/wElOvyv' },
        { name: 'CX-18腕龍鞭打隨機強化組', url: 'https://lin.ee/R3Uf7Ys' },
        { name: 'BXG-01烈焰飛鳳S', url: 'https://lin.ee/91G8cDn' },
        { name: 'BX-51炫風發射器 黑綠', url: 'https://lin.ee/ub34Vey' },
        { name: 'BX-40發射器（酒紅）', url: 'https://lin.ee/pCeQbWz' },
        { name: 'BX-35隨機強化組Vol.', url: 'https://lin.ee/QtIsgeh' },
        { name: 'BX-50天堂日輪隨機強化組', url: 'https://lin.ee/uZ52zTl' },
        { name: 'BX-33皓戰猛虎', url: 'https://lin.ee/XjDe5ma' },
        { name: 'BX-18 X炫風發射器', url: 'https://lin.ee/53RYxU7' },
        { name: 'BX-26獨角刺心', url: 'https://lin.ee/TOIAF5e' },
        { name: 'BX-00暴風天馬3-70RA', url: 'https://lin.ee/7meLFUn' },
        { name: 'BX-32寬型極限衝擊戰鬥盤', url: 'https://lin.ee/vtPi2tx' },
      ],
    },
    {
      store: 'Funbox Toys-大葉高島屋',
      storeUrl: 'https://linevoom.line.me/user/_dfhvm3-8_klezJkCHLv3-mEhPQWOR9DGFr40SPA',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）21:00',
      items: [
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/oQftDUW' },
        { name: 'BX-50 天堂日輪 隨機強化', url: 'https://lin.ee/z7Td3Gr' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/8WUY2KX' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/7OSuRof' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/rwPDcO1' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/8UeJWKh' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/OPYEc578' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/WBMWFcS' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/RxHvaPM' },
        { name: 'BX-35 隨機強化組Vol.04', url: 'https://lin.ee/NzS2cxEK' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/tvERf3U' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/vjuf0wr' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/NYvqvZ2' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/ZAbzxDV' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/SE0DFSI' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/87xUH1V' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/8fEeQs2' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/NWIqavM' },
      ],
    },
    {
      store: '來玩聚-北車地下街',
      storeUrl: 'https://linevoom.line.me/user/_dXjo38IGuVk3obdbWWB8DVc86lCei15_6UkRuW8',
      startTime: '2026年08月28日（五）12:00 ~ 08月29日（六）20:30',
      items: [
        { name: 'BX-40 發射器(酒紅)左迴', url: 'https://lin.ee/zTfTvpD' },
        { name: 'BX-51 黑綠旋風拉線發射器', url: 'https://lin.ee/zBGbaSa' },
        { name: 'BX-35 隨機強化組Vol.4', url: 'https://lin.ee/NmI5pyX' },
        { name: 'CX-18 腕龍鞭打', url: 'https://lin.ee/5iP45eb' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/X1Ypoek' },
        { name: 'UX-20 榮耀戰神', url: 'https://lin.ee/OXTR7l3' },
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/S8yfj1o' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/ZOZ34q6' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/ZHURiDd' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/t9Fn7iw' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/tNvOVbj' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/yio9ZGk' },
        { name: 'BX-18 發射器', url: 'https://lin.ee/WeVBkyE' },
      ],
    },
    {
      store: 'Funbox天母三越店',
      storeUrl: 'https://linevoom.line.me/user/_dXYFKzVX-ldfgeUOor_McfFTE_yJP7d54nPjxpQ',
      items: [
        { name: 'UX-20 榮耀女武神', url: 'https://lin.ee/wBvFN2J' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/VwXtHSw' },
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/qt4wA06' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/7pFR6OL' },
        { name: 'BX-40 發射器', url: 'https://lin.ee/nlNO7zU' },
        { name: 'BX-51旋風發射器 黑綠', url: 'https://lin.ee/PIePz1a' },
        { name: 'BX-50 天堂日輪隨機強化組', url: 'https://lin.ee/uaBy3wh' },
        { name: 'CX-18 腕龍鞭打隨機強化組', url: 'https://lin.ee/OnkeSxw' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/yAnYvar' },
        { name: 'BX-35 隨機強化組 Vol.', url: 'https://lin.ee/sjANMnS' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/yDuMJqF' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/O6A5Qu4' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/x9ejtfu' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/uiraH5M' },
        { name: 'BX-57 3on3 戰術陀螺收納盒', url: 'https://lin.ee/7wo6hoR' },
        { name: 'BX-25 戰鬥陀螺專業收納包', url: 'https://lin.ee/t5DzC6W' },
        { name: 'BX-10極限衝擊戰鬥盤', url: 'https://lin.ee/tn0jSx7' },
      ],
    },
    {
      store: 'Funbox-信義A8店(陀螺販售)',
      storeUrl: 'https://linevoom.line.me/user/_dfItqTWWpJgcZPNYg_b3_xlBeXDhlwTDTicnfSU',
      items: [{ name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/q97O5u7' }],
    },
    {
      store: 'Funbox 遠百信義A13',
      storeUrl: 'https://linevoom.line.me/user/_dZWTe6za3_22gXVkl46uAq37zC6nwkQQCwZnBoA',
      items: [
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/rmqmcJK' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/OTcb95I' },
        { name: 'BX-18旋風發射器', url: 'https://lin.ee/p1ae3r1' },
        { name: 'BX-40發射器(酒紅)', url: 'https://lin.ee/qrLVL4d' },
        { name: 'BX-51旋風發射器 黑綠', url: 'https://lin.ee/qO377rA' },
        { name: 'CX-18腕龍鞭打 隨機強化組', url: 'https://lin.ee/6JxC0z7' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/sIwKwXDU' },
        { name: 'UX-19子彈獅鷲H', url: 'https://lin.ee/xbiVtHb' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/TiVMoAc' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/TZt71nw' },
      ],
    },
    {
      store: 'Funbox 三越站前店',
      storeUrl: 'https://linevoom.line.me/user/_dTQ_Ar8kG3TZeWoB_i2PtLW_TclZiMtldppUzAQ',
      items: [
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/XPI38YQE' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/xxBXwm8' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/VsLOyOe' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/Yu0oI9O' },
      ],
    },
    {
      store: 'Funbox 天母SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_db3MM1gifrvefmBbBLPWOhPAw0aPUL9K3IvLDTk',
      items: [
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/QKy5qn7' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/PzRjMLL' },
        { name: 'BX-40 發射器（酒紅）', url: 'https://lin.ee/roNvWF1' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/vBSvCHb' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/vRy7Kmb' },
        { name: 'BX-57 3V3對戰收納盒（黑）', url: 'https://lin.ee/WrnejoZ' },
        { name: 'UX-02 惡魔戰鎚', url: 'https://lin.ee/pbZhX9A' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/5JE24Ce' },
      ],
    },
    {
      store: 'Funbox 美麗華',
      storeUrl: 'https://linevoom.line.me/user/_dS6PecGuAayr8FMQ6NoCcETN1oXZ0zgwun4Uivc',
      items: [
        { name: 'UX-21惡魔冥界改造組', url: 'https://lin.ee/Suuh0WP' },
        { name: 'UX11 衝擊龍神 9-60 LR', url: 'https://lin.ee/WcqjWdy' },
        { name: 'UX19 子彈獅鷲 H', url: 'https://lin.ee/uDrqsH5' },
        { name: 'CX13 龍王閃擊BK 1-50 I', url: 'https://lin.ee/WuY9vYd' },
        { name: 'CX18 腕龍鞭打 5-70 Nr', url: 'https://lin.ee/wlBvX5F' },
        { name: 'BX10 極限衝擊戰鬥盤', url: 'https://lin.ee/wq8Xh16' },
        { name: 'BX18 黑色旋風發射器', url: 'https://lin.ee/UMF2FOh' },
        { name: 'BX25 戰鬥陀螺X專業收納包(黑)', url: 'https://lin.ee/o6FCEYD' },
        { name: 'BX26 獨角刺心 5-60 GP', url: 'https://lin.ee/VXF1Iub' },
        { name: 'BX33 皓戰白虎 3-60 U', url: 'https://lin.ee/ULt1jCP' },
        { name: 'BX35 玄冥戰甲 抽抽包', url: 'https://lin.ee/WZOYsDS' },
        { name: 'BX37雙重極限衝擊戰鬥盤豪華組', url: 'https://lin.ee/WEOWkxg' },
        { name: 'BX40 左迴旋拉條發射器L', url: 'https://lin.ee/7QwGv71' },
        { name: 'BX45武士魂斬6-70M', url: 'https://lin.ee/SQmvkTm' },
        { name: 'BX51黑×綠色旋風發射器', url: 'https://lin.ee/NsXneVi' },
        { name: 'BX57 3V3對戰收納盒 黑', url: 'https://lin.ee/oBrBdCY' },
        { name: 'BXG01 烈焰飛鳳S 3-80 T', url: 'https://lin.ee/oRVQpRZ' },
        { name: 'BXG04 銀牙烈虎S 4-80 P', url: 'https://lin.ee/tJBIH2W' },
      ],
    },
  ],
  新北市: [
    {
      store: 'Funbox樹林秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dSj7fhnsKdDEm1q2ehrYEJTOyrm4OuI2NFsN3I0',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（日）21:00',
      items: [
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/SR4uIfA' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/VBlLELk' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/UpULXTP' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/5zFKgpP' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/S4uOZ39' },
        { name: 'BX-50 天堂日輪 隨機強化組', url: 'https://lin.ee/sTP2QCw' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/yNH9nGh' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/yHG2AoXK' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/stOnQIN' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/sFPY1KT' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/wSSyb6O' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/XeIJeWC' },
      ],
    },
    {
      store: 'Funbox 新店誠品店',
      storeUrl: 'https://linevoom.line.me/user/_dWQGqQnQTk4Tc7wJjzrBXKS145vBC93TlHkNG5E',
      startTime: '2026年08月28日（五）11:00',
      items: [
        { name: 'BX-57 3V3 對戰收納盒 黑色版 （不含陀螺）', url: 'https://lin.ee/NZhMQ4x' },
        { name: 'BX-25 專業收納包（不含陀螺）', url: 'https://lin.ee/UMZIIXH' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/r5My0c3' },
        { name: 'BX-45武士魂斬 6-70M', url: 'https://lin.ee/sOWP5E27' },
        { name: 'BX-51 蒼旋風發射器/黑綠', url: 'https://lin.ee/PBP4vgc' },
        { name: 'BX-40 發射器 左迴旋 酒紅', url: 'https://lin.ee/T003MNz' },
        { name: 'BXG-01烈焰飛鳳S', url: 'https://lin.ee/oL6Aqh7' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/nIkFU1w' },
      ],
    },
    {
      store: 'FunBox Toys-汐止遠雄店',
      storeUrl: 'https://linevoom.line.me/user/_dXWlFT8AyCrEdtsk_fRRUYuqERc8rWDzx3c6DUA',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）22:00',
      items: [
        { name: 'BX-50 天堂日輪 隨機強化組', url: 'https://lin.ee/pM2tdPFu' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/OSj26JJ' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/StkURkyV' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/wjRuEzM' },
        { name: 'BX-35 隨機強化組Vol.4', url: 'https://lin.ee/S2hCveN' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/Rka7bKF' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/qX1qW6ar' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/SUqCHvm' },
        { name: 'BX-00 暴風天馬3-70R', url: 'https://lin.ee/Op8jS9I' },
        { name: 'BX-51 旋風發射器（黑綠）', url: 'https://lin.ee/9lxk0P4R' },
        { name: 'BXG-01 烈燄飛鳳s', url: 'https://lin.ee/RsQCHAX1' },
        { name: 'BX-40 發射器（酒紅）', url: 'https://lin.ee/zSArdFn' },
        { name: 'BXG-04 銀牙烈虎s', url: 'https://lin.ee/qXJgkTI' },
        { name: 'BX-57 3V3對戰收納盒（黑）', url: 'https://lin.ee/wQnsGbN' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/OW8V3OF' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/VCgeEGN' },
        { name: 'BX-25 戰鬥陀螺x專業收納包', url: 'https://lin.ee/YY093fd' },
      ],
    },
    {
      store: 'Funbox-中和環球',
      storeUrl: 'https://linevoom.line.me/user/_dSg6slLn5Zg47l9CPlGC-LezlX4EP3fmltKvQRs',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）21:00',
      items: [
        { name: 'BX-18 X旋風發射器.', url: 'https://lin.ee/o1RgS8q' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/tnp36hW' },
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/nGikFntS' },
        { name: 'UX-02惡魔戰錘', url: 'https://lin.ee/ufiWrfX' },
        { name: 'UX-11衝擊龍神 9-60LR 豪華組', url: 'https://lin.ee/TEak2ba' },
        { name: 'BX-45武士魂斬', url: 'https://lin.ee/tkvs2R4' },
        { name: 'BX-25 專業收納包', url: 'https://lin.ee/o2UyqHH' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/96NCPQM' },
      ],
    },
    {
      store: 'Funbox&Sanrio板橋大遠百',
      storeUrl: 'https://linevoom.line.me/user/_dblyPGfsKpebVOKvBaP8gs72hysvg-G0EVYLyv4',
      items: [
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/xheASvX' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/seyqhlS' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/UwnH92e' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/pkDSIq5' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/R6VQbEl' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/rNAmAgV' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/Y3gWQVr' },
        { name: 'BX-50 天堂日輪 隨機強化組', url: 'https://lin.ee/sSNr3M8' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/z7kLKuv6' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/TsnvZ4M' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/qcpfI4D' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/5mYI87f' },
        { name: 'UX-01 蒼龍爆刃', url: 'https://lin.ee/nno3V7j' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/XjabcZaU' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/PtcBTDnb' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/nhavyh4' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/8PXerlh' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/s8ZDxf1' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/p1SwEvf' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/6pTWBQKN' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/qTLQJZR' },
      ],
    },
    {
      store: 'Funbox板橋遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dUcATZnmDAam7Low6HB0-JXZC1DzUJEbh8hA8Gg',
      items: [
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/Y05Wj8Y' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/Qvbk3nN' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/VLh1vvg' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/qBG4FaP' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/8IIXGfM' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/wF4KXAF' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/OpaV6iw' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/QjRGGvY' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/7c1CEKX' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/PGysA24' },
        { name: 'BX-35 隨機強化組Vol.', url: 'https://lin.ee/zkA1diW' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/6AW4HFq' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/Xg4XnVj' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/pYB3npJf' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/5l2uJTo' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/To1hX0R' },
      ],
    },
    {
      store: 'Funbox淡水禮萊廣場店',
      storeUrl: 'https://linevoom.line.me/user/_dU6uuJLZc-sttPrdL6hfb8pOoMDCcgdNWEtYPKA',
      items: [
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/QpMHTmE' },
        { name: 'BX-25戰鬥陀螺X專業收納包 –', url: 'https://lin.ee/rpbuthp' },
        { name: 'BX-57 3V3對戰收納盒 黑 –', url: 'https://lin.ee/S5by05z' },
        { name: 'UX-02惡魔戰錘 –', url: 'https://lin.ee/tt3JwKY' },
        { name: 'UX-11 衝擊龍神 豪華組 –', url: 'https://lin.ee/WOIyQGp' },
        { name: 'BX-40發射器(酒紅)', url: 'https://lin.ee/sD4myRp' },
        { name: 'BX-51 旋風發射器 黑綠 –', url: 'https://lin.ee/OAc3mIX' },
        { name: 'CX-18 腕龍鞭打 隨機強化組 –', url: 'https://lin.ee/YRMdB78' },
      ],
    },
    {
      store: 'FUNBOX 比漾廣場店',
      storeUrl: 'https://linevoom.line.me/user/_dQbxr4jKpXDT3BtXULflBCgU9GujoUvNaAUOOZo',
      items: [
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/zgEQ89e' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/Nm4CM17' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/n9ZpUIN' },
        { name: 'BX-40 發射器(酒紅)(左迴旋)', url: 'https://lin.ee/SJvwalr' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/UOi10z8' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/PE3rp5q' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/vpWYBNP' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/VJ0S3ZW' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/plZxdYa' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/yT22UFH' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/7UyojyK' },
      ],
    },
  ],
  桃園市: [
    {
      store: 'Funbox-桃園站前三越',
      storeUrl: 'https://linevoom.line.me/user/_dQTwDiZdgoMiaxHmu-STwWJF69wlpmOwL0IjMoY',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）21:00',
      items: [{ name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/Q5emiZW' }],
    },
    {
      store: 'Funbox Toy-桃園環球A8店',
      storeUrl: 'https://linevoom.line.me/user/_dWWqORTPgThK__JAqyRDK9PX4ReZqnOFc28vpaE',
      items: [
        { name: 'UX-19子彈獅鷲', url: 'https://lin.ee/tM0mVd4' },
        { name: 'BXG-04銀牙烈虎', url: 'https://lin.ee/TmsRpyR' },
        { name: 'BXG-01烈焰飛鳳', url: 'https://lin.ee/8x5KSVsE' },
        { name: 'BX-00暴風天馬', url: 'https://lin.ee/8ER1QuO' },
        { name: 'BX-35 隨機強化組vol.', url: 'https://lin.ee/nBQY3g3' },
        { name: 'BX-33皓戰猛虎', url: 'https://lin.ee/ZYF4GxZ' },
        { name: 'BX-26獨角刺心', url: 'https://lin.ee/nothX47' },
        { name: 'BX-51旋風發射器 黑綠', url: 'https://lin.ee/x955Fpp1' },
        { name: 'BX-18右迴旋發射器', url: 'https://lin.ee/VDqoOxe' },
        { name: 'BX-50天堂日輪 強化組', url: 'https://lin.ee/6aFQv6D' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/re25qAN' },
        { name: 'BX-40 左迴旋發射器 酒紅', url: 'https://lin.ee/Z8Wd4DP' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/TbNPa1U' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/zE7aNua' },
        { name: 'BX-57 3V3 對戰收納盒 黑色版 （不含陀螺）', url: 'https://lin.ee/OfwqexV' },
        { name: 'BX-25 專業收納包（不含陀螺）', url: 'https://lin.ee/zQCD7oi' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/pkIvt4V' },
      ],
    },
    {
      store: 'Funbox toys - 桃園台茂店',
      storeUrl: 'https://linevoom.line.me/user/_dZrp8IBATlHOFZaobLCYRrXE5m7abD4dD2ItWm8',
      items: [
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/Y93g5wt' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/P7rOuVh' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/TTSoyC6' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/WidK7uJ' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/6QICHOc' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/RFm6sJz' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/ZL4MGnT' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/NXIZfwR' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/ZL83gdu' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/oe1rROj' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/5kLcUeK' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/vgY7gpL' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/YuEcVlg' },
      ],
    },
    {
      store: 'Funbox-桃園遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dZCpDMgUi2_f6JEnQze2nP22nJV-G1o8rHLmpFE',
      items: [
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/owfL0b9' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/ToLuAFK' },
        { name: 'BX-57 3V3對戰收納盒 黑(無附陀螺)', url: 'https://lin.ee/XrhIPwU' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/vlX7J45' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/ttdRdRj' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/PyYikOh' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/pzfYrUE' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/NtL3Rvw' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/ry95prd' },
      ],
    },
    {
      store: 'Funbox 中壢大江店',
      storeUrl: 'https://linevoom.line.me/user/_daOwg6Nz08TwGFzWoVR264J1CWj5Lp8g0Lgf-QM',
      items: [
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/X3V6TIq' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/rvYT35b' },
        { name: 'BX-32寬型極限戰鬥盤', url: 'https://lin.ee/OiTBBXc' },
        { name: 'BX-40 發射器（左迴旋', url: 'https://lin.ee/R0OUf8x' },
        { name: 'BX-51炫風發射器（黑綠', url: 'https://lin.ee/x5svE3D' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/tjgcao3' },
        { name: 'BX-37雙重極限衝極戰鬥盤 豪華組', url: 'https://lin.ee/6x2cdD31' },
        { name: 'BX-45武士斬魂', url: 'https://lin.ee/PwFibxe' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/RcEVMVc' },
        { name: 'UX-20 榮耀武神', url: 'https://lin.ee/nua1iCT' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/6SuMVwo' },
        { name: 'BX-30 X發射器改造型握把（黑紅）', url: 'https://lin.ee/w8eDenX' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/nvd275v' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/QlKLYZV' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/PRPdton' },
      ],
    },
    {
      store: 'FunBox-中壢SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_dcSEo3ibPOyoQAAsta4srlSCIdiLnKQqsbk8mog',
      items: [
        { name: 'BX-51 旋風發射器 黑綠-', url: 'https://lin.ee/pxwo4Wl' },
        { name: 'BX-40 發射器(酒紅)-', url: 'https://lin.ee/s3kHvFSI' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/s8QwyPx' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/PwZT5TJ' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/vblHE1h' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/5LvgjZB' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/sq88iNR' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/TPoHJzZ' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/rPLgZay' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/yvmPkRc' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/8pTwVTg' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/WHmSYoE' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/7CZLOoe' },
      ],
    },
    {
      store: 'FunBox-桃園環球A19店',
      storeUrl: 'https://linevoom.line.me/user/_dQguBN50HV7T3jjTaZbJKVwoET6cJJH2Kj43Y2E',
      items: [
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/Wva6PwV' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/RCIsfoA' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/vnCEMVI' },
        { name: 'BX-32寬型極限衝擊戰鬥盤', url: 'https://lin.ee/oqk3P9aT' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/VdbJAwU' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/5jb9ka9' },
        { name: 'BX-35 隨機強化組Vol.', url: 'https://lin.ee/PHFLgAV' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/YKAQcXz' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/qMm25ZE' },
        { name: 'BX-50 天堂日輪 隨機強化組', url: 'https://lin.ee/Zo4TFwx' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/R8cbDnC' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/O937eti' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/ZPzg9Hj' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/SDPeyGc' },
        { name: 'BX-57 3V3對戰收納盒(黑)', url: 'https://lin.ee/RB9WSG9' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/VISc8gJ' },
      ],
    },
  ],
  新竹市: [
    {
      store: 'Funbox-新竹遠雄店',
      storeUrl: 'https://linevoom.line.me/user/_dYdtj10kF6eWUWfcb0xr0dYExX6yYVDk1EksNTU',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）21:00',
      items: [
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/zpKVnDo' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/8yA5lm6' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/7Dc5Y3x' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/6dwXuN0' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/nBfAH4d' },
        { name: 'UX-11 衝擊龍神豪華組', url: 'https://lin.ee/sxB3FS5' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/RxZbvrr' },
      ],
    },
    {
      store: 'Funbox 新竹巨城店',
      storeUrl: 'https://linevoom.line.me/user/_dSYAGjN3DhBtiB8tU2pa3kl5yoRdBG7ucZNUZvo',
      items: [],
    },
    {
      store: 'Funbox-新竹遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dYjgWm0vwMyoPEcmLUOBhOQ55A0WaB7EuLfW5Mw',
      items: [
        { name: 'BX-10 極限衝擊戰鬥盤-', url: 'https://lin.ee/XgQ7Frk' },
        { name: 'BX-25 戰鬥陀螺X專業收納包-', url: 'https://lin.ee/VHCI3nV' },
        { name: 'BX-57 3V3對戰收納盒 黑-', url: 'https://lin.ee/RusLNjiQ' },
        { name: 'BX-51 旋風發射器 黑綠-', url: 'https://lin.ee/vXHogcq' },
        { name: 'CX-18 腕龍鞭打 隨機強化組-', url: 'https://lin.ee/Wy5ANhK' },
        { name: 'UX-19 子彈獅鷲H-', url: 'https://lin.ee/PDuEWPU' },
        { name: 'UX-02 惡魔戰錘-', url: 'https://lin.ee/z8SP0Fc' },
        { name: 'BX-40 發射器(酒紅)-', url: 'https://lin.ee/oFWfevv' },
        { name: 'UX-21 惡魔冥界改造組-', url: 'https://lin.ee/9cp66iv' },
      ],
    },
  ],
  台中市: [
    {
      store: 'Funbox 台中港三井店',
      storeUrl: 'https://linevoom.line.me/user/_dXDniXt3Xu0U5lkXYliBBHGQRD2FtCUnVVbXPhY',
      startTime: '2026年08月28日（五）11:00 ~ 08月29日（六）20:30',
      items: [
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/n3TPmTn' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/UICzg33' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/S1dOPWk' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/QjhI9MP' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/OtVbNFm' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/pmfKR4L' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/zGvMqnX' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/8V9g0ju' },
      ],
    },
    {
      store: 'Funbox麗寶一期店',
      startTime: '2026/08/28~2026/08/29',
      items: [
        { name: 'BX-25戰鬥陀螺X專業收納包(原價$850)：', url: 'https://lin.ee/tbARevuY' },
        { name: 'BX-57 3V3對戰收納盒(黑)(原價$250)：', url: 'https://lin.ee/7PAip29' },
        { name: 'CX-18腕龍鞭打 隨機強化組(原價$350)：', url: 'https://lin.ee/PLQYVpm' },
        { name: 'UX-02 惡魔戰錘陀螺(原價$395)：', url: 'https://lin.ee/RUJjSVC' },
        { name: 'UX-11衝擊龍神豪華組(原價$550)：', url: 'https://lin.ee/6VmsizF' },
        { name: 'UX-19 子彈獅鷲(原價$550)：', url: 'https://lin.ee/P7fw5aM' },
        { name: 'BXG-01 烈焰飛鳳S(原價$350)：', url: 'https://lin.ee/5Ke8LGi' },
        { name: 'BXG-04 銀牙烈虎S(原價$350)：', url: 'https://lin.ee/xXegem6' },
        { name: 'BX-26獨角刺心(原價$295)：', url: 'https://lin.ee/RiAlVw2' },
        { name: 'BX-33皓戰猛虎(原價$295)：', url: 'https://lin.ee/VjVuOKz' },
        { name: 'BX-35 隨機強化組Vol.04(原價$295)：', url: 'https://lin.ee/W3iWsdI' },
        { name: 'BX-50天堂日輪 隨機強化組 (原價$350)：', url: 'https://lin.ee/w0xmLqC' },
        { name: 'UX-20榮耀武神LF(原價$595)：', url: 'https://lin.ee/XTgMC8r' },
        { name: 'BX-00暴風天馬3-70RA  (原價$595)：', url: 'https://lin.ee/X2LfqUV' },
        { name: 'BX-10極限衝擊戰鬥盤  (原價$850)：', url: 'https://lin.ee/omF0FgC' },
        { name: 'BX-51 旋風發射器(黑綠)(原價$250)：', url: 'https://lin.ee/Wa89sUG' },
        { name: 'BX-18 X旋風發射器(原價$250)：', url: 'https://lin.ee/tYg9wIb' },
        { name: 'BX-40 發射器(酒紅)(原價$250)：', url: 'https://lin.ee/snLupZo' },
      ],
    },
    {
      store: 'Funbox 豐原太平洋店',
      startTime: '2026/08/28~2026/08/29',
      items: [
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/9HXGvi5l' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/XOfQ427' },
        { name: 'BX-40 左迴旋發射器（酒紅）', url: 'https://lin.ee/6Z8wRa4' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/v2OM6vl' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/5EBHBfm' },
        { name: 'BXG 04 銀牙烈虎S', url: 'https://lin.ee/9hgwLla' },
      ],
    },
    {
      store: 'Funbox 台中中友店',
      startTime: '2026/08/28~2026/08/29',
      items: [
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/u0Y0AmI' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/Rdm6dIG' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/UUQ68s0' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/nfE6YpW' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/ST2wbmi' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/wt7ZN3z' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/7ZaToqn' },
        {
          name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組',
          url: 'https://lin.ee/sfMgKmZ',
        },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/7CdsZLv' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/t4OJ2UN' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/qiV9cNm' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/xeNSl1i' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/QptFYwJ' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/6Ug3BP7' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/7FKDLby' },
      ],
    },
    {
      store: 'Funbox 新光三越台中店',
      startTime: '2026/08/28~2026/08/29',
      items: [
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/xejG4ag' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/6Xmqwex' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/sGmIqhI' },
        { name: 'BX-25 專業收納包', url: 'https://lin.ee/OcW8qBt' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/9va1Ept' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/RywHgiK' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/q6IRMoJ' },
        { name: 'BX-35 隨機強化組vol.4', url: 'https://lin.ee/v8H81Hp' },
        {
          name: 'BX-37 雙重極限衝擊戰鬥盤豪華組',
          url: 'https://lin.ee/pmUV4F5',
        },
        { name: 'BX-40 發射器 酒紅', url: 'https://lin.ee/rTUxOCT' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/NAuyK4O' },
        { name: 'BX-50 天堂日輪隨機強化組', url: 'https://lin.ee/OrDhGF5' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/9d8fh4t' },
        { name: 'BX-57 3V3對戰收納盒', url: 'https://lin.ee/qOCGbo8' },
        { name: 'UX-03 魔導神杖', url: 'https://lin.ee/WhA1YMF' },
        { name: 'UX-11 衝擊龍神豪華組', url: 'https://lin.ee/7cQpFng' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/6TBJaAM' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/WQncIAy' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/SzdgXPy' },
      ],
    },
    {
      store: 'Funbox 廣三SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_dUpKOzSR_s9Wca-q8vJLgOSM-UGMJNMonlEK_Nw',
      items: [
        {
          name: 'BX-25戰鬥陀螺X專業收納包(原價$850)：',
          url: 'https://lin.ee/tbARevuY',
        },
        {
          name: 'BX-57 3V3對戰收納盒(黑)(原價$250)：',
          url: 'https://lin.ee/7PAip29',
        },
        {
          name: 'CX-18腕龍鞭打 隨機強化組(原價$350)：',
          url: 'https://lin.ee/PLQYVpm',
        },
        {
          name: 'UX-02 惡魔戰錘陀螺(原價$395)：',
          url: 'https://lin.ee/RUJjSVC',
        },
        {
          name: 'UX-11衝擊龍神豪華組(原價$550)：',
          url: 'https://lin.ee/6VmsizF',
        },
        { name: 'UX-19 子彈獅鷲(原價$550)：', url: 'https://lin.ee/P7fw5aM' },
        { name: 'BXG-01 烈焰飛鳳S(原價$350)：', url: 'https://lin.ee/5Ke8LGi' },
        { name: 'BXG-04 銀牙烈虎S(原價$350)：', url: 'https://lin.ee/xXegem6' },
        { name: 'BX-26獨角刺心(原價$295)：', url: 'https://lin.ee/RiAlVw2' },
        { name: 'BX-33皓戰猛虎(原價$295)：', url: 'https://lin.ee/VjVuOKz' },
        {
          name: 'BX-35 隨機強化組Vol.04(原價$295)：',
          url: 'https://lin.ee/W3iWsdI',
        },
        {
          name: 'BX-50天堂日輪 隨機強化組 (原價$350)：',
          url: 'https://lin.ee/w0xmLqC',
        },
        { name: 'UX-20榮耀武神LF(原價$595)：', url: 'https://lin.ee/XTgMC8r' },
        {
          name: 'BX-00暴風天馬3-70RA  (原價$595)：',
          url: 'https://lin.ee/X2LfqUV',
        },
        {
          name: 'BX-10極限衝擊戰鬥盤  (原價$850)：',
          url: 'https://lin.ee/omF0FgC',
        },
        {
          name: 'BX-51 旋風發射器(黑綠)(原價$250)：',
          url: 'https://lin.ee/Wa89sUG',
        },
        {
          name: 'BX-18 X旋風發射器(原價$250)：',
          url: 'https://lin.ee/tYg9wIb',
        },
        {
          name: 'BX-40 發射器(酒紅)(原價$250)：',
          url: 'https://lin.ee/snLupZo',
        },
      ],
    },
    {
      store: 'FUNBOX 台中遠百店',
      storeUrl: 'https://linevoom.line.me/user/_ddG1EBaa4iGasgQdKDdnXo50Y24dW74VXnJuAro',
      items: [
        { name: 'BX-00【暴風天馬3-70RA】：', url: 'https://lin.ee/ZoRMNno' },
        { name: 'BX-10【極限衝擊戰鬥盤】：', url: 'https://lin.ee/PazsXZR' },
        { name: 'BX-18【X旋風發射器】：', url: 'https://lin.ee/W4i4zJG' },
        { name: 'BX-25【戰鬥陀螺X專業收納包】：', url: 'https://lin.ee/Udwwj2L' },
        { name: 'BX-26【獨角刺心】：', url: 'https://lin.ee/uBo4rvL' },
        { name: 'BX-32【寬型極限衝擊戰鬥盤】：', url: 'https://lin.ee/RqUsm85' },
        { name: 'BX-33【皓戰猛虎】：', url: 'https://lin.ee/PWOHTju' },
        { name: 'BX-37【雙重極限衝擊戰鬥盤豪華組】：', url: 'https://lin.ee/tg1LB7K' },
        { name: 'BX-45【武士魂斬】：', url: 'https://lin.ee/6v6rB8l' },
        { name: 'BX-50【天堂日輪 隨機強化組】：', url: 'https://lin.ee/QQaFt8F' },
        { name: 'BX-51【旋風發射器(黑綠)】：', url: 'https://lin.ee/SsQcVGJ' },
        { name: 'BX-57【3V3對戰收納盒-黑】：', url: 'https://lin.ee/YJzAq52' },
        { name: 'BXG-01【烈焰飛鳳S】：', url: 'https://lin.ee/tBApiM8' },
        { name: 'BXG-04【銀牙烈虎S】：', url: 'https://lin.ee/yuMDan0' },
        { name: 'UX-02【惡魔戰錘】：', url: 'https://lin.ee/p213YpN' },
        { name: 'UX-11【衝擊龍神豪華組】：', url: 'https://lin.ee/Wo4vwGH' },
        { name: 'UX-19【子彈獅鷲H】：', url: 'https://lin.ee/ukxITe9' },
        { name: 'UX-20【榮耀武神LF】：', url: 'https://lin.ee/ppsPrIS4' },
      ],
    },
    {
      store: 'Funbox 台中lalaport',
      storeUrl: 'https://linevoom.line.me/user/_dWbmVBOBVpcGPA3UWP953LsGWVx32VkrDcGrqRQ',
      items: [
        {
          name: 'UX-20 榮耀武神LF 購買資格 *使用優惠券限店員操作* | Funbox 台中lalaport | 官方帳號優惠券',
          url: 'https://lin.ee/zMWwj3Q',
        },
      ],
    },
    {
      store: 'Funbox 文心秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dVbUMDyduUeLgyWJWRb0k8o55Sa-xzXFMnCJxpE',
      items: [
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/zpHV14P' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/ow30B8I' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/7jhYc9J' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/YCkSnxT' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/xKtpC92' },
        { name: 'BX-35 隨機強化組Vol.04', url: 'https://lin.ee/wQmF3i9e' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/9bQd93j' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/PQIxWUM' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/pVcRYFJ' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/pTo7Drq' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/R8vn6brE' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/rEZFKfG' },
      ],
    },
  ],
  嘉義市: [
    {
      store: 'Funbox-嘉義遠東',
      storeUrl: 'https://www.facebook.com/profile.php?id=61592768918548',
      items: [],
    },
  ],
  高雄市: [
    {
      store: '義大世界購物廣場 fun box 義大2館',
      storeUrl: 'https://www.facebook.com/profile.php?id=100057653970900',
      items: [],
    },
    {
      store: 'Funbox-夢時代店',
      storeUrl: 'https://linevoom.line.me/user/_dVHpcOhwVrBQ3ZY1xQBHuGMcluZ-yMcOSsSnRfU',
      items: [{ name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/8XmzPmr' }],
    },
  ],
  宜蘭縣: [
    {
      store: 'Funbox 宜蘭新月店',
      storeUrl: 'https://linevoom.line.me/user/_dTS4fzrnBtUOuG-T_J22hfcZSdxunoOsypVfgRg',
      items: [{ name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/RJDBg0h' }],
    },
  ],
  新竹縣: [
    {
      store: 'Funbox 竹北遠東店',
      storeUrl: 'https://linevoom.line.me/user/_deu1wnG4xXho1I98-nH_PZKQ0gl-iAoehGDIHxA',
      items: [
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/SZ10LFe' },
        { name: 'BXG-04 銀牙烈虎s', url: 'https://lin.ee/StHF8FL' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/YBVrhAsv' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/upXF1Qv' },
        { name: 'BXG-01 烈焰飛鳳s', url: 'https://lin.ee/8Nu8BLy' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/PHR7Ezs' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/pWPSx2t' },
        { name: 'BX-35 隨機強化組Vol.', url: 'https://lin.ee/tf7TuZU' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/xtZieLE' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/SMfKXdM' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/QAYR2sw' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/XNK33sO' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/8wN1IHF' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/xeZBWXX' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/Z9pnKPO' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/TLoW8e6' },
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/nhfKgsb' },
      ],
    },
    {
      store: 'funbox 享平方店',
      storeUrl: 'https://linevoom.line.me/user/_dfuDiJPQBJn4ih1iarevDIEIB9XvR-_q44VI6bE',
      items: [
        { name: 'UX-20 榮耀女武神', url: 'https://lin.ee/9TxB7HY' },
        { name: 'UX-19 子彈獅鷲 5-70H', url: 'https://lin.ee/tVF7Ab89' },
        { name: 'UX-11衝擊龍神', url: 'https://lin.ee/QjARoZv' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/oglOIFpu' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/RLYLApx' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/qyZHUHfF' },
        { name: 'CX-18 隨機強化組', url: 'https://lin.ee/ojoZUnO' },
        { name: 'BX-35隨機強化組 Vol.', url: 'https://lin.ee/y2nw5fI' },
        { name: 'BX-50隨機強化組Vol.', url: 'https://lin.ee/xVwAhL9' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/sih46Kr' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/sJ6EQOZ' },
        { name: 'BX-00 暴風天馬3 7-70RA', url: 'https://lin.ee/6lKYX5r' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/uRbM2KZ' },
        { name: 'BX-51 旋風發射器', url: 'https://lin.ee/ouE4EYH' },
        { name: 'BX-40 左迴旋拉條發射器', url: 'https://lin.ee/yqlfKmbM' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/veYGOwF' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/TFzHbfF' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/7MAc5tU' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/Ohute8Jn' },
      ],
    },
  ],
  台南市: [
    {
      store: 'Funbox Toys-台南南紡店',
      storeUrl: 'https://linevoom.line.me/user/_dZ41RU2UUbwJMwmDe4O30FG3iEb647ohcj6Txq4',
      items: [
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/6P88wlg' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/8K7fqBn' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/rQivEfl' },
        { name: 'BX-25 戰鬥陀螺X專業收納包', url: 'https://lin.ee/NMSECJv' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/te0zeQM' },
        { name: 'BX-32 寬型極限衝擊戰鬥盤', url: 'https://lin.ee/NQngBdu' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/wjNb17d' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/x03sqRv' },
        { name: 'BX-40 發射器(酒紅)', url: 'https://lin.ee/NE7Dwl7u' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/5OBDlmX' },
        { name: 'BX-51 旋風發射器 黑綠', url: 'https://lin.ee/UrgNP13' },
        { name: 'BX-57 3V3對戰收納盒 黑', url: 'https://lin.ee/vHQ8iOD' },
        { name: 'CX-18 腕龍鞭打 隨機強化組', url: 'https://lin.ee/oBvdgWL' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/Zt7J2Pn' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/pcVXTlD' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/VhXG0yz' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/wEbR0Q7' },
      ],
    },
  ],
  苗栗縣: [
    {
      store: 'Funbox Toys-苗栗尚順店',
      storeUrl: 'https://linevoom.line.me/user/_dVHyXrJlEjwLilMjmYrRy8BYKPofyQgAgsWd8Xk',
      items: [
        { name: 'BX-25 專業收納包', url: 'https://lin.ee/SGrSo04' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/7ywJfSN' },
        { name: 'BX-57 3V3對戰收納盒黑', url: 'https://lin.ee/tMbYyuo' },
      ],
    },
  ],
};
