export interface GiveawayItem {
  name: string;
  url: string;
}

export interface StoreGiveaway {
  store: string;
  storeUrl?: string;
  startTime?: string;
  items: GiveawayItem[];
}

export interface Region {
  name: string;
}

export const REGIONS: Region[] = [
  { name: '全部' },
  { name: '台北市' },
  { name: '新北市' },
  { name: '桃園市' },
  { name: '新竹市' },
  { name: '新竹縣' },
  { name: '苗栗縣' },
  { name: '彰化縣' },
  { name: '雲林縣' },
  { name: '宜蘭縣' },
  { name: '台中市' },
  { name: '嘉義市' },
  { name: '台南市' },
  { name: '高雄市' },
  { name: '屏東縣' },
  { name: '花蓮縣' },
  { name: '台東縣' },
  { name: '澎湖縣' },
];

export const GIVEAWAYS: Record<string, StoreGiveaway[]> = {
  台北市: [
    {
      store: 'Funbox-台北大巨蛋',
      storeUrl: 'https://www.facebook.com/profile.php?id=61593737335376',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/TauMeeJ' },
        { name: 'BX-46 無限衝擊對戰組', url: 'https://lin.ee/U3ppnbc' },
        { name: 'BX-23 鳳凰飛翼 豪華組', url: 'https://lin.ee/NXCPMML' },
        { name: 'BX-39 護城龍神', url: 'https://lin.ee/xMg6FSs' },
        { name: 'BX-44 三角強襲', url: 'https://lin.ee/VvgzDtS' },
        { name: 'BX-13 騎士長槍', url: 'https://lin.ee/X1v1t8m' },
        { name: 'BX-16 王蛇鞭尾 隨機強化組', url: 'https://lin.ee/OCQr8EZ' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/XNczmlg' },
        { name: 'BX-21 惡魔鎖鏈改造組', url: 'https://lin.ee/9LbkCtl' },
        { name: 'BX-50 天堂日輪 隨機強化組', url: 'https://lin.ee/Nq9s8U3' },
        { name: 'BX-00 丘巴卡 風暴兵', url: 'https://lin.ee/sDaSYu3' },
        { name: 'BX-00 歐比王 葛里維斯將軍', url: 'https://lin.ee/WwDBzw0' },
        { name: 'BX-00 美國隊長 紅浩克', url: 'https://lin.ee/RmQi7Cx' },
        { name: 'BX-00 終極蜘蛛人 綠惡魔', url: 'https://lin.ee/Uw3ZLvP' },
        { name: 'BXG-22 龍騎士S', url: 'https://lin.ee/r4eJ9Ia' },
        { name: 'UX-10 騎士圓甲改造組', url: 'https://lin.ee/vGCViQp' },
        { name: 'UX-11 衝擊龍神 豪華組', url: 'https://lin.ee/xbDC2Ri' },
        { name: 'UX-14 天蠍長矛0-70Z', url: 'https://lin.ee/ymaAoQA' },
        { name: 'UX-08 霜輝銀狼', url: 'https://lin.ee/X9B7fEF' },
        { name: 'UX-13 魔像奇岩', url: 'https://lin.ee/ty5CxH5' },
        { name: 'UX-06 雄獅巔峰', url: 'https://lin.ee/QZumkum' },
        { name: 'UX-09 武士星劍 豪華組', url: 'https://lin.ee/YKj14yy' },
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/ZGTOwTU' },
        { name: 'UX-15 鮫鯊狂鱗改造組', url: 'https://lin.ee/qi5CPRL' },
        { name: 'CX-02 魔導至尊', url: 'https://lin.ee/nXJbLW9' },
        { name: 'CX-11 帝王威能', url: 'https://lin.ee/yI8BXBV' },
        { name: 'CX-12 鳳凰閃焰', url: 'https://lin.ee/Ns87Dai' },
        { name: 'CX-05 隨機強化組 Vol.6', url: 'https://lin.ee/tRAzma1' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/nbX5JsL' },
        { name: 'CX-08 隨機強化組 Vol.7', url: 'https://lin.ee/5GzHj9T' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/WBosPIK' },
      ],
    },
    {
      store: 'Funbox-忠孝SOGO店',
      storeUrl: 'https://www.facebook.com/funboxsogo',
      startTime: '',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/Teeti1U' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/Q3x58xY' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/6myV5gy' },
      ],
    },
    {
      store: 'Funbox-南港潤泰',
      storeUrl: 'https://linevoom.line.me/user/_dSeRV-7dSwPAS21zhFTEZS9TU0cjb1gBLwEML9A',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [],
    },
    {
      store: 'Funbox LaLaport南港',
      storeUrl: 'https://linevoom.line.me/user/_dVgaAWKsM1ofi6bVa7iJV1_zOspCOrdSv0vgXKw',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [],
    },
    {
      store: 'Funbox Toys-大葉高島屋',
      storeUrl: 'https://linevoom.line.me/user/_dfhvm3-8_klezJkCHLv3-mEhPQWOR9DGFr40SPA',
      startTime: '',
      items: [],
    },
    {
      store: '來玩聚-北車地下街',
      storeUrl: 'https://linevoom.line.me/user/_dXjo38IGuVk3obdbWWB8DVc86lCei15_6UkRuW8',
      startTime: '抽選時間：2026/09/11 12:00~2026/09/12 20:30',
      items: [
        { name: 'UX-21 惡魔幽冥改造組', url: 'https://lin.ee/YUyfSal' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/65obJEn' },
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/ZDvzc3y' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/n3AkNVM' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/5I0u8UA' },
      ],
    },
    {
      store: 'Funbox天母三越店',
      storeUrl: 'https://linevoom.line.me/user/_dXYFKzVX-ldfgeUOor_McfFTE_yJP7d54nPjxpQ',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00 福音戰士改造組', url: 'https://lin.ee/rFVhsbI' },
        { name: 'BX-00 暴風天馬', url: 'https://lin.ee/629xw4m' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/WYNMaUp' },
        { name: 'BX-00 蒼龍神劍V2', url: 'https://lin.ee/yxZblNk' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/Pxw2I5hu' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/rU3f6Ng' },
      ],
    },
    {
      store: 'Funbox-信義A8店(陀螺販售)',
      storeUrl: 'https://linevoom.line.me/user/_dfItqTWWpJgcZPNYg_b3_xlBeXDhlwTDTicnfSU',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [
        { name: 'CX-12 鳳凰閃焰', url: 'https://lin.ee/qtETM0Z' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/8ui3pQS' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/NsYCTEy' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/U0irnFS' },
      ],
    },
    {
      store: 'Funbox 遠百信義A13',
      storeUrl: 'https://linevoom.line.me/user/_dZWTe6za3_22gXVkl46uAq37zC6nwkQQCwZnBoA',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [
        { name: 'BX-37雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/7AmqRzi' },
        { name: 'BX-00蒼龍神劍', url: 'https://lin.ee/67lhgQeG' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/yMELNp6' },
        { name: 'UX-20榮耀武神LF', url: 'https://lin.ee/o91HeXX' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/O9OVpCU' },
      ],
    },
    {
      store: 'Funbox 三越站前店',
      storeUrl: 'https://linevoom.line.me/user/_dTQ_Ar8kG3TZeWoB_i2PtLW_TclZiMtldppUzAQ',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [{ name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/wNVQFEw' }],
    },
    {
      store: 'Funbox 天母SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_db3MM1gifrvefmBbBLPWOhPAw0aPUL9K3IvLDTk',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/y4j0PVB' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/sW8NexE' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/uq6jtZa' },
      ],
    },
    {
      store: 'Funbox 美麗華',
      storeUrl: 'https://linevoom.line.me/user/_dS6PecGuAayr8FMQ6NoCcETN1oXZ0zgwun4Uivc',
      startTime: '抽選/購買時間 2026/09/04 11:00 - 2026/09/05 21:00',
      items: [],
    },
    {
      store: 'Funbox 三越南西店',
      storeUrl: 'https://linevoom.line.me/user/_dXRCeNI62-wxECClrgjwMfi8HnY2ow5Onw6aC1A',
      startTime: '抽選/購買時間 2026/09/04 11:00 - 2026/09/05 21:00',
      items: [],
    },
    {
      store: 'Fun box忠孝SOGO',
      storeUrl: 'https://linevoom.line.me/user/_dZR3EbkBX6ugUrxVH_Qo47n8xYDp-95FYmhlIWM',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/Teeti1U' },
        { name: 'BX-00 蒼龍神劍', url: 'https://lin.ee/Q3x58xY' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/6myV5gy' },
      ],
    },
  ],
  新北市: [
    {
      store: 'Funbox樹林秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dSj7fhnsKdDEm1q2ehrYEJTOyrm4OuI2NFsN3I0',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/nMMo9F9' },
        { name: 'BX-25 專業收納包', url: 'https://lin.ee/vyKYuXu' },
        { name: 'BX-57 3v3對戰收納盒', url: 'https://lin.ee/x6lajAo' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/rsycL2q' },
        { name: 'BX-10 極限衝擊戰鬥盤', url: 'https://lin.ee/qVQi9m3' },
        { name: 'BXG-01 烈焰飛鳳', url: 'https://lin.ee/svvpyy8' },
        { name: 'BX-30發射器握把（黑紅）', url: 'https://lin.ee/6sbALkLw' },
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/7dR60o7' },
        { name: 'BX-18 X旋風發射器', url: 'https://lin.ee/8Mgc2Ra' },
        { name: 'BX-00 蒼龍神劍V2', url: 'https://lin.ee/sCU4pitK' },
        { name: 'BX-45武士魂斬', url: 'https://lin.ee/7jUJs9F' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/U0394RC' },
        { name: 'CX-13龍王閃擊', url: 'https://lin.ee/UYv5QPl' },
      ],
    },
    {
      store: 'Funbox新店誠品店',
      storeUrl: 'https://linevoom.line.me/user/_dWQGqQnQTk4Tc7wJjzrBXKS145vBC93TlHkNG5E',
      startTime: '抽選時間：2026/09/11 11:00 起',
      items: [
        { name: 'BX-37 雙重極限衝擊戰鬥盤豪華組', url: 'https://lin.ee/RyYyWOo' },
        { name: 'CX-12 鳳凰閃焰 Z9-80WW', url: 'https://lin.ee/vk3CI4g' },
        { name: 'BX-00 蒼龍神劍 3-60F', url: 'https://lin.ee/r1IXPQE' },
      ],
    },
    {
      store: 'FunBox Toys-汐止遠雄店',
      storeUrl: 'https://linevoom.line.me/user/_dXWlFT8AyCrEdtsk_fRRUYuqERc8rWDzx3c6DUA',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/UHqMK5X' },
        { name: 'BX-00暴風天馬3-70R', url: 'https://lin.ee/n6US1jV' },
        { name: 'BXG-04銀牙烈虎s', url: 'https://lin.ee/58XYS5A' },
        { name: 'BXG-01烈燄飛鳳s', url: 'https://lin.ee/NNAyTM8' },
        { name: 'BX-26獨角刺心', url: 'https://lin.ee/V7BEn2I' },
        { name: 'CX-13龍王閃擊', url: 'https://lin.ee/UizxRku' },
        { name: 'UX-21惡魔冥界改造組', url: 'https://lin.ee/8552VhL' },
        { name: 'BX-00蒼龍神劍', url: 'https://lin.ee/7PHWVG7' },
      ],
    },
    {
      store: 'Funbox-中和環球店',
      storeUrl: 'https://linevoom.line.me/user/_dSg6slLn5Zg47l9CPlGC-LezlX4EP3fmltKvQRs',
      startTime: '抽籤時間：2026/09/11 11:00~2026/09/12 20:30',
      items: [
        { name: 'UX-21 惡魔幽冥', url: 'https://lin.ee/qro4Qkz' },
        { name: 'BX-00 蒼龍神劍V2', url: 'https://lin.ee/Sgnos11' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/UdigxI5' },
        { name: 'BX-37雙重極限衝擊戰鬥盤', url: 'https://lin.ee/vmGyKot' },
      ],
    },
    {
      store: 'Funbox板橋大遠百',
      storeUrl: 'https://linevoom.line.me/user/_dblyPGfsKpebVOKvBaP8gs72hysvg-G0EVYLyv4',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/nwZ8UAn' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/wzZcF5u' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/7rYQ9mm' },
        { name: 'CX-12 鳳凰閃焰', url: 'https://lin.ee/SLbhLeD' },
      ],
    },
    {
      store: 'Funbox板橋遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dUcATZnmDAam7Low6HB0-JXZC1DzUJEbh8hA8Gg',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/7Qp0lON' },
        { name: 'BX-00蒼龍神劍v2', url: 'https://lin.ee/p6Hm7YO' },
        { name: 'CX-00新世紀福音戰士改造組', url: 'https://lin.ee/vAF5QKG' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/yKmsW9Y' },
        { name: 'UX-21惡魔冥界改造組', url: 'https://lin.ee/Q7Ubro4' },
      ],
    },
    {
      store: 'Funbox淡水禮萊廣場店',
      storeUrl: 'https://linevoom.line.me/user/_dU6uuJLZc-sttPrdL6hfb8pOoMDCcgdNWEtYPKA',
      startTime: '',
      items: [],
    },
    {
      store: 'FUNBOX 比漾廣場店',
      storeUrl: 'https://linevoom.line.me/user/_dQbxr4jKpXDT3BtXULflBCgU9GujoUvNaAUOOZo',
      startTime: '',
      items: [
        { name: 'CX-00新世紀福音戰士改造組', url: 'https://lin.ee/9jLWHeT' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/udna5wGR' },
      ],
    },
  ],
  桃園市: [
    {
      store: 'Funbox-桃園站前三越',
      storeUrl: 'https://linevoom.line.me/user/_dQTwDiZdgoMiaxHmu-STwWJF69wlpmOwL0IjMoY',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/RyT9nk9' },
        { name: 'UX-02 惡魔戰錘', url: 'https://lin.ee/RcMEFmW' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/NpUNAS1' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/x6yzH8p' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/9l323EP' },
        { name: 'BX-50 天堂日輪隨機強化組', url: 'https://lin.ee/qUn33fe' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/taF4Bk6' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/QXxp4qV' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/VixMUsb' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/nQmhrsZ' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/VJRYDec' },
      ],
    },
    {
      store: 'Funbox Toy-桃園環球A8店',
      storeUrl: 'https://linevoom.line.me/user/_dWWqORTPgThK__JAqyRDK9PX4ReZqnOFc28vpaE',
      startTime: '抽選時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/WN5WcJR' },
        { name: 'BX-00 蒼龍神劍', url: 'https://lin.ee/9kinAbh' },
        { name: 'BXG-04 銀牙烈虎', url: 'https://lin.ee/VjyP3Zs' },
      ],
    },
    {
      store: 'Funbox toys - 桃園台茂店',
      storeUrl: 'https://linevoom.line.me/user/_dZrp8IBATlHOFZaobLCYRrXE5m7abD4dD2ItWm8',
      startTime: '',
      items: [
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/UriwrYo' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/8XsGAXt' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/zttbMMn' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/zlsVocK' },
      ],
    },
    {
      store: 'Funbox-桃園遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dZCpDMgUi2_f6JEnQze2nP22nJV-G1o8rHLmpFE',
      startTime: '抽選/購買時間 2026/09/04 11:00 - 2026/09/05 21:00',
      items: [],
    },
    {
      store: 'Funbox 中壢大江店',
      storeUrl: 'https://linevoom.line.me/user/_daOwg6Nz08TwGFzWoVR264J1CWj5Lp8g0Lgf-QM',
      startTime: '抽選&購買時間 2026/09/04 11:00 - 2026/09/05 21:00',
      items: [],
    },
    {
      store: 'FunBox-中壢SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_dcSEo3ibPOyoQAAsta4srlSCIdiLnKQqsbk8mog',
      startTime: '抽選/購買時間 2026/09/04 11:00 - 2026/09/05 21:00',
      items: [],
    },
    {
      store: 'FunBox-桃園環球A19店',
      storeUrl: 'https://linevoom.line.me/user/_dQguBN50HV7T3jjTaZbJKVwoET6cJJH2Kj43Y2E',
      startTime: '',
      items: [],
    },
  ],
  新竹市: [
    {
      store: 'Funbox-新竹遠雄店',
      storeUrl: 'https://linevoom.line.me/user/_dYdtj10kF6eWUWfcb0xr0dYExX6yYVDk1EksNTU',
      startTime: '抽選時間：2026/09/11~2026/09/12',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組-1395元', url: 'https://lin.ee/ofEN0zN' },
        { name: 'UX-21惡魔冥界改造組-895元', url: 'https://lin.ee/5mqMzNZ' },
        { name: 'BX-00 蒼龍神劍 3-60F-350元', url: 'https://lin.ee/nM1oXtf' },
      ],
    },
    {
      store: 'Funbox 新竹巨城店',
      storeUrl: 'https://linevoom.line.me/user/_dSYAGjN3DhBtiB8tU2pa3kl5yoRdBG7ucZNUZvo',
      startTime: '',
      items: [],
    },
    {
      store: 'Funbox-新竹遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dYjgWm0vwMyoPEcmLUOBhOQ55A0WaB7EuLfW5Mw',
      startTime: '抽選時間：2026/09/11~2026/09/12（營業時間 11:00~21:00）',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/Wyve9VK' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/ppQFtam' },
      ],
    },
  ],
  台中市: [
    {
      store: 'Funbox 台中港三井',
      storeUrl: 'https://linevoom.line.me/user/_dXDniXt3Xu0U5lkXYliBBHGQRD2FtCUnVVbXPhY',
      startTime: '抽籤時間&使用期限 2026/09/11 11:00 - 2026/09/12 20:30',
      items: [
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/7WCLpWq' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/9mQ9dqB' },
      ],
    },
    {
      store: 'Funbox麗寶一期店',
      storeUrl: 'https://linevoom.line.me/user/_dZD8OLWoBDH7CMfvg3nqfJoIb3wQMGpZ_V7DOOI',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'BX-00新福音戰士（改造組）', url: 'https://lin.ee/nFb30Ey' },
        { name: 'CX-13龍王閃擊', url: 'https://lin.ee/rnE5Hl5' },
        { name: 'BX-00蒼龍神劍', url: 'https://lin.ee/UVyu6GN' },
      ],
    },
    {
      store: 'Funbox 豐原太平洋店',
      storeUrl: 'https://linevoom.line.me/user/_dWUEiTQIz0C550q-X-t3o65-r0CLa8-fBL6b6u8',
      startTime: '',
      items: [],
    },
    {
      store: 'Funbox 台中中友店',
      storeUrl: 'https://linevoom.line.me/user/_dVExgXo7x7ugfZBDIYzfRF8XR9geWiZncXXAkNM',
      startTime: '抽選時間：2026/09/11 10:30~2026/09/12 21:00',
      items: [],
    },
    {
      store: 'Funbox 新光三越台中店',
      storeUrl: 'https://linevoom.line.me/user/_dcavY93jrqjYaLVO8JR44m7jxZNARF__lfYuyIo',
      startTime: '',
      items: [
        { name: 'CX-00新世紀福音戰士改造組', url: 'https://lin.ee/TD7feHx' },
        { name: 'CX-13龍王閃擊', url: 'https://lin.ee/xBXRHTN' },
        { name: 'CX-12鳳凰閃焰', url: 'https://lin.ee/5tprgOZ' },
        { name: 'BX-00蒼龍神劍3-60F V2', url: 'https://lin.ee/nPFDpKX' },
        { name: 'BX-37雙重極限衝擊戰鬥盤 豪華組', url: 'https://lin.ee/55h9bXF' },
      ],
    },
    {
      store: 'Funbox 廣三SOGO店',
      storeUrl: 'https://linevoom.line.me/user/_dUpKOzSR_s9Wca-q8vJLgOSM-UGMJNMonlEK_Nw',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00新世紀福音戰士改造組(原價$1395)', url: 'https://lin.ee/8aMGnIR' },
        { name: 'UX-21惡魔冥界改造組(原價$895)', url: 'https://lin.ee/TFhnOX3' },
        { name: 'CX-13龍王閃擊(原價$495)', url: 'https://lin.ee/WTpWADL' },
        { name: 'BX-00蒼龍神劍3-60F V2(原價$350)', url: 'https://lin.ee/PEh5xzw' },
        { name: 'UX-19 子彈獅鷲(原價$550)', url: 'https://lin.ee/7v6B5V9' },
        { name: 'BXG-01 烈焰飛鳳S(原價$350)', url: 'https://lin.ee/x8AeEnS' },
        { name: 'BXG-04 銀牙烈虎S(原價$350)', url: 'https://lin.ee/8lrmbQT' },
      ],
    },
    {
      store: 'FUNBOX 台中遠百店',
      storeUrl: 'https://linevoom.line.me/user/_ddG1EBaa4iGasgQdKDdnXo50Y24dW74VXnJuAro',
      startTime: '',
      items: [
        { name: 'BX-00【蒼龍神劍3-60F V2】', url: 'https://lin.ee/qfTQm6t' },
        { name: 'CX-13【龍王閃擊】', url: 'https://lin.ee/te5g1Xi' },
        { name: 'BX-00【暴風天馬3-70RA】', url: 'https://lin.ee/VXvmMY9' },
        { name: 'BX-37【雙重極限衝擊戰鬥盤豪華組】', url: 'https://lin.ee/Vsf2yCI' },
        { name: 'BXG-01【烈焰飛鳳S】', url: 'https://lin.ee/sU4NcKu' },
        { name: 'BXG-04【銀牙烈虎S】', url: 'https://lin.ee/pj1KJb7' },
        { name: 'UX-02【惡魔戰錘】', url: 'https://lin.ee/W36U3CS' },
        { name: 'CX-00【新世紀福音戰士改造組】', url: 'https://lin.ee/7GeMM36' },
      ],
    },
    {
      store: 'Funbox 台中lalaport',
      storeUrl: 'https://linevoom.line.me/user/_dWbmVBOBVpcGPA3UWP953LsGWVx32VkrDcGrqRQ',
      startTime: '',
      items: [],
    },
    {
      store: 'Funbox 文心秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dVbUMDyduUeLgyWJWRb0k8o55Sa-xzXFMnCJxpE',
      startTime: '',
      items: [],
    },
  ],
  嘉義市: [
    {
      store: 'Funbox Toys-嘉義遠東店',
      storeUrl: 'https://linevoom.line.me/user/_dVzi6SpAv9EDTDhGlf38KyYzGRC3R0O0O6zxlno',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 20:30',
      items: [
        { name: 'BX-00 蒼龍神劍', url: 'https://lin.ee/Qls6R6V' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/pVfZbJ6' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/WeYu7JB' },
      ],
    },
    {
      store: 'Funbox 嘉義三越店',
      storeUrl: 'https://linevoom.line.me/user/_dVZ_jIBO92xnDLzsC9JfjVWMgA2TNLQ2hncb3Ok',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'BX-00蒼龍神劍3-60F V2', url: 'https://lin.ee/Olyo4pX' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/N4zI9Ue' },
      ],
    },
  ],
  高雄市: [
    {
      store: '義大世界購物廣場 fun box 義大2館',
      storeUrl: 'https://www.facebook.com/profile.php?id=100057653970900',
      startTime: '',
      items: [],
    },
    {
      store: 'Funbox-夢時代店',
      storeUrl: 'https://linevoom.line.me/user/_dVHpcOhwVrBQ3ZY1xQBHuGMcluZ-yMcOSsSnRfU',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [{ name: 'CX-00 新世紀福音戰士改造組 1395元', url: 'https://lin.ee/O1cMbf4' }],
    },
    {
      store: 'Funbox-漢神巨蛋店',
      storeUrl: 'https://linevoom.line.me/user/_dZuBlwRH9v-DXFkhIH9m1xAU7En6xl4R3qc363s',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00新世紀福音戰士改造組 $1395', url: 'https://lin.ee/nXdw5Sx' },
        { name: 'BX-00 蒼龍神劍3-60F V2 $350', url: 'https://lin.ee/y12Oomf' },
      ],
    },
    {
      store: 'Funbox 高雄大立店',
      storeUrl: 'https://linevoom.line.me/user/_dQjEieF9ohNmyCT1yYbOpfT_jw3DHpatmfmuM5o',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 20:30',
      items: [
        { name: 'BX-00蒼龍神劍3-60F V2  350元', url: 'https://lin.ee/zMvVOQx' },
        { name: 'CX-00新世福音戰士改造組 1395元', url: 'https://lin.ee/wRBZy0v' },
        { name: 'CX-13龍王閃擊 495元', url: 'https://lin.ee/YaqfU9G' },
        { name: 'UX-02 惡魔戰錘 395元', url: 'https://lin.ee/7GO4j7c' },
      ],
    },
    {
      store: 'Funbox高雄sogo店',
      storeUrl: 'https://linevoom.line.me/user/_dV2_iZGnvicFJijn62vXHA57ANIeliHDGI7gnRo',
      startTime: '',
      items: [{ name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/T5CrB1d' }],
    },
    {
      store: 'Funbox 高雄大遠百店',
      storeUrl: 'https://linevoom.line.me/user/_dYOR2VczscGNCah5bglUoA62Gj_YR_lq2R-UoMs',
      startTime: '',
      items: [],
    },
    {
      store: '來玩聚-新楠店',
      storeUrl: 'https://linevoom.line.me/user/_deAwpKm1kymi62-wvUqTCvK1LpCSk5bvwxAubMQ',
      startTime: '抽選時間：2026/09/11 10:00~2026/09/12 21:00',
      items: [{ name: 'BX-00 蒼龍神劍V2 - 原價$350', url: 'https://lin.ee/oWeYBs8' }],
    },
    {
      store: 'funbox大魯閣新光',
      storeUrl: 'https://linevoom.line.me/user/_dQ0ecVMFJ6V-NPSlxQbE5hqjsBH-WOBO5HdSv4Q',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [{ name: 'CX-00 新世紀福音戰士改造組 售價1395元', url: 'https://lin.ee/XURwiUg' }],
    },
    {
      store: 'Funbox-高雄漢神店',
      storeUrl: 'https://linevoom.line.me/user/_dZFySf-_Iy1JFk7B9OJx3p-R8KIqsjXVk6wMx_s',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [],
    },
    {
      store: '來玩聚鳳山店',
      storeUrl: 'https://linevoom.line.me/user/_dYHKZsEifm4hbpeUB6f8DAHE-NaYM-f4lmS_yxc',
      startTime: '',
      items: [],
    },
    {
      store: '來玩聚 楠梓店',
      storeUrl: 'https://linevoom.line.me/user/_dVPoSlHQT0aqmC-EZpckQXYHAMiL802BM23S7qk',
      startTime: '',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/zYhcxRZP' },
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/5tiuXjv' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/Z3iK5cP' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/X4F6fos' },
      ],
    },
  ],
  宜蘭縣: [
    {
      store: 'Funbox 宜蘭新月店',
      storeUrl: 'https://linevoom.line.me/user/_dTS4fzrnBtUOuG-T_J22hfcZSdxunoOsypVfgRg',
      startTime: '抽選時間：2026/09/11 11:00 起',
      items: [
        { name: 'BX-50 天堂日輪 隨機強化組', url: 'https://lin.ee/yp0yDSz' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/SG6VTOM' },
        { name: 'UX-19 子彈獅鷲H', url: 'https://lin.ee/9EuCF5n' },
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/wlr7HAE' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/ZpmUeY2' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/9POeXce' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/xg2AtHJ' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/RxSpLhl' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/plxRmQO' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/8l5ZgOi' },
      ],
    },
  ],
  新竹縣: [
    {
      store: 'Funbox 竹北遠東店',
      storeUrl: 'https://linevoom.line.me/user/_deu1wnG4xXho1I98-nH_PZKQ0gl-iAoehGDIHxA',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/WZcKHxw' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/ylbms4i' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/5aiicgx' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/NoxUMlh' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/WaOcOXM' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/ZLPUmoH' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/nAdCSiL' },
      ],
    },
    {
      store: 'funbox 享平方店',
      storeUrl: 'https://linevoom.line.me/user/_dfuDiJPQBJn4ih1iarevDIEIB9XvR-_q44VI6bE',
      startTime: '',
      items: [
        { name: 'CX-00新世紀福音戰士 戰鬥陀螺套組', url: 'https://lin.ee/PQu29Ba' },
        { name: 'UX-21 惡魔幽冥改造組', url: 'https://lin.ee/v5BaU1O' },
        { name: 'UX-20 榮耀女武神', url: 'https://lin.ee/SbZDBQ7' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/QejSZDj' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/nY7KyiO' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/w6KDcki' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/sTZukVs' },
        { name: 'BX-00 暴風天馬3 7-70RA', url: 'https://lin.ee/w2IZhiv' },
        { name: 'BX-00 蒼龍神劍3-60F', url: 'https://lin.ee/saFUAqzM' },
      ],
    },
  ],
  台南市: [
    {
      store: 'Funbox Toys-台南南紡店',
      storeUrl: 'https://linevoom.line.me/user/_dZ41RU2UUbwJMwmDe4O30FG3iEb647ohcj6Txq4',
      startTime: '抽選/購買時間 2026/09/11 11:00 - 2026/09/12 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2 $350', url: 'https://lin.ee/sOES69Y' },
        { name: 'BX-26 獨角刺心 $295', url: 'https://lin.ee/R8qN6Pe' },
        { name: 'BX-33 皓戰猛虎 $295', url: 'https://lin.ee/xBUpv9v' },
        { name: 'BX-37 雙重極限衝擊戰鬥盤 豪華組 $2750', url: 'https://lin.ee/u3wwmAC' },
        { name: 'BX-45 武士魂斬 $325', url: 'https://lin.ee/5DYWzKP' },
        { name: 'CX-13 龍王閃擊 $495', url: 'https://lin.ee/nIFAjIM' },
        { name: 'UX-02 惡魔戰錘 $395', url: 'https://lin.ee/uqPGQfF' },
        { name: 'UX-19 子彈獅鷲H $550', url: 'https://lin.ee/874mNB8' },
        { name: 'UX-20 榮耀武神LF $595', url: 'https://lin.ee/xsKMnPI' },
        { name: 'UX-21 惡魔冥界改造組 $895', url: 'https://lin.ee/YEjbfuf' },
        { name: 'BXG-01 烈焰飛鳳S $350', url: 'https://lin.ee/nm8hxAb' },
        { name: 'BXG-04 銀牙烈虎S $350', url: 'https://lin.ee/83Kw1XX' },
        { name: 'CX-00 福音戰士改造組 $1395', url: 'https://lin.ee/y2Z1zC9' },
      ],
    },
    {
      store: 'funbox-台南新天地',
      startTime: '抽選時間：2026/09/11 11:00 起',
      items: [],
    },
    {
      store: 'Funbox 台南三井店',
      storeUrl: 'https://linevoom.line.me/user/_dTp06Slhdio7LDmd8xKxz3J2mw25-ZMRXZtXQ9I',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 20:30',
      items: [],
    },
    {
      store: 'FUNBOX 台南遠百',
      storeUrl: 'https://linevoom.line.me/user/_dWKgSOpFJ9bwQuysxkGH0jnCsb22vMfW7kuZDzU',
      startTime: '抽選時間：2026/09/11 11:00 起',
      items: [{ name: '9/11 CX-00新世紀福音戰士改造組', url: 'https://lin.ee/Wu5v4s6' }],
    },
  ],
  苗栗縣: [
    {
      store: 'Funbox Toys-苗栗尚順店',
      storeUrl: 'https://linevoom.line.me/user/_dVHyXrJlEjwLilMjmYrRy8BYKPofyQgAgsWd8Xk',
      startTime: '',
      items: [],
    },
  ],
  彰化縣: [
    {
      store: '來玩聚-彰化店',
      storeUrl: 'https://linevoom.line.me/user/_deL1i2Bb8uUCbeQ10yCnEvVLz_iZbXwvFtNNTRM',
      startTime: '抽選時間：2026/09/11 10:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/RjyQdUc' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/ptsOv5k' },
        { name: 'UX-21 惡魔冥界改造組', url: 'https://lin.ee/X7IyEQJ' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/tkA8Cms' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/5S5iDzB' },
        { name: 'BX-33  皓戰猛虎', url: 'https://lin.ee/9hfYqY0' },
        { name: 'UX-02  惡魔戰錘', url: 'https://lin.ee/6jqBx8o' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/Span7zb' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/QoPxlVQ' },
      ],
    },
    {
      store: '來玩聚-員林店',
      storeUrl: 'https://linevoom.line.me/user/_dar-0z1aYQPkB0W-BiwgwDp6XsDKAdehbmupEaI',
      startTime: '抽選/購買時間 2026/09/11 10:00 - 2026/09/12 21:00',
      items: [],
    },
  ],
  雲林縣: [
    {
      store: '來玩聚斗六店',
      storeUrl: 'https://linevoom.line.me/user/_ddu256ZXwJCBqOeIfKwY6QYdeIvbrVOmBRIOKfo',
      startTime: '抽選時間：2026/09/11 10:00~2026/09/12 21:00',
      items: [
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/QXcuze1' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/qucHkZ1' },
        { name: 'BX-00蒼龍神劍3-60F V2', url: 'https://lin.ee/YxTVT2G' },
      ],
    },
  ],
  屏東縣: [
    {
      store: 'funbox屏東太平洋',
      storeUrl: 'https://linevoom.line.me/user/_dTnMNq0eoiZ5jnuQaFUz2oVpxylrT13ojfI_Ko8',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'UX-00 新世紀福音戰士改造組 售價1395元', url: 'https://lin.ee/8F28eaV' },
        { name: 'BX-00 蒼龍神劍3-60F V2 售價350元', url: 'https://lin.ee/VYNow4o' },
      ],
    },
    {
      store: 'Funbox 屏東環球店',
      storeUrl: 'https://linevoom.line.me/user/_dfq4IRS_qaEaR4Svk0SKsB78xW9x2-lkU1wSpKU',
      startTime: '抽選時間：2026/09/11 11:00~2026/09/12 21:00',
      items: [
        { name: 'BX-00 蒼龍神劍3-60F V2 $350', url: 'https://lin.ee/rMFSI42' },
        { name: 'CX-13 龍王閃擊 $495', url: 'https://lin.ee/8Pp9KkQ' },
        { name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/7iP00az' },
      ],
    },
  ],
  花蓮縣: [
    {
      store: 'funbox 花蓮店',
      startTime: '',
      items: [{ name: 'CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/PeKYB6U' }],
    },
  ],
  澎湖縣: [
    {
      store: 'Funbox澎湖3號港店',
      startTime: '抽選時間：2026/09/11 10:30~2026/09/12 21:30',
      items: [
        { name: 'BX-00 暴風天馬3-70RA', url: 'https://lin.ee/uJHjHCb' },
        { name: 'BX-00 蒼龍神劍3-60F V2', url: 'https://lin.ee/UOLUzqg' },
        { name: 'BX-26 獨角刺心', url: 'https://lin.ee/vW52UTm' },
        { name: 'BX-33 皓戰猛虎', url: 'https://lin.ee/WKJYGP4' },
        { name: 'BX-45 武士魂斬', url: 'https://lin.ee/UXZG8Jv' },
        { name: 'UX-20 榮耀武神LF', url: 'https://lin.ee/OrUwaIT' },
        { name: 'CX-13 龍王閃擊', url: 'https://lin.ee/N7vab0U' },
        { name: 'BXG-01 烈焰飛鳳S', url: 'https://lin.ee/V8TRwUn' },
        { name: 'BXG-04 銀牙烈虎S', url: 'https://lin.ee/T6Olfng' },
      ],
    },
  ],
  台東縣: [
    {
      store: 'Funbox 台東秀泰店',
      storeUrl: 'https://linevoom.line.me/user/_dWiMasxT4CrK1ogY11eoxXAVvwO-U9Fchsvba6o',
      startTime: '',
      items: [{ name: '9/11 CX-00 新世紀福音戰士改造組', url: 'https://lin.ee/PeKYB6U' }],
    },
    {
      store: '來玩聚-台東家樂福',
      startTime: '',
      items: [],
    },
  ],
};
