module.exports = [
  ['嘉義市', 'Funbox Toys-嘉義遠東店', 'https://linevoom.line.me/user/_dVzi6SpAv9EDTDhGlf38KyYzGRC3R0O0O6zxlno'],
  ['嘉義市', 'Funbox 嘉義三越店', 'https://linevoom.line.me/user/_dVZ_jIBO92xnDLzsC9JfjVWMgA2TNLQ2hncb3Ok'],
  ['台南市', 'Funbox 台南三井店', 'https://linevoom.line.me/user/_dTp06Slhdio7LDmd8xKxz3J2mw25-ZMRXZtXQ9I'],
  ['台南市', 'FUNBOX 台南遠百', 'https://linevoom.line.me/user/_dWKgSOpFJ9bwQuysxkGH0jnCsb22vMfW7kuZDzU'],
  ['高雄市', 'Funbox-漢神巨蛋店', 'https://linevoom.line.me/user/_dZuBlwRH9v-DXFkhIH9m1xAU7En6xl4R3qc363s'],
  ['高雄市', 'Funbox 高雄大立店', 'https://linevoom.line.me/user/_dQjEieF9ohNmyCT1yYbOpfT_jw3DHpatmfmuM5o'],
  ['高雄市', 'Funbox高雄sogo店', 'https://linevoom.line.me/user/_dV2_iZGnvicFJijn62vXHA57ANIeliHDGI7gnRo'],
  ['高雄市', 'Funbox 高雄大遠百店', 'https://linevoom.line.me/user/_dYOR2VczscGNCah5bglUoA62Gj_YR_lq2R-UoMs'],
  ['高雄市', 'Funbox-高雄漢神店', 'https://linevoom.line.me/user/_dZFySf-_Iy1JFk7B9OJx3p-R8KIqsjXVk6wMx_s'],
  ['屏東縣', 'funbox屏東太平洋', 'https://linevoom.line.me/user/_dTnMNq0eoiZ5jnuQaFUz2oVpxylrT13ojfI_Ko8'],
  ['屏東縣', 'Funbox 屏東環球店', 'https://linevoom.line.me/user/_dfq4IRS_qaEaR4Svk0SKsB78xW9x2-lkU1wSpKU'],
  ['台東縣', 'Funbox 台東秀泰店', 'https://linevoom.line.me/user/_dWiMasxT4CrK1ogY11eoxXAVvwO-U9Fchsvba6o'],
  ['高雄市', 'funbox大魯閣新光', 'https://linevoom.line.me/user/_dQ0ecVMFJ6V-NPSlxQbE5hqjsBH-WOBO5HdSv4Q'],
  ['台中市', 'Funbox 文心秀泰店', 'https://linevoom.line.me/user/_dVbUMDyduUeLgyWJWRb0k8o55Sa-xzXFMnCJxpE'],
  ['台中市', 'Funbox 豐原太平洋店', 'https://linevoom.line.me/user/_dWUEiTQIz0C550q-X-t3o65-r0CLa8-fBL6b6u8'],
  ['台中市', 'Funbox麗寶一期店', 'https://linevoom.line.me/user/_dZD8OLWoBDH7CMfvg3nqfJoIb3wQMGpZ_V7DOOI'],
  ['台中市', 'Funbox 新光三越台中店', 'https://linevoom.line.me/user/_dcavY93jrqjYaLVO8JR44m7jxZNARF__lfYuyIo'],
  ['台中市', 'Funbox 台中遠雄店', 'https://linevoom.line.me/user/_da-4j4bX8VxHQN54is9WglGxqo3ISQzKaJK2vA0'],
  ['台中市', 'Funbox 台中港三井', 'https://linevoom.line.me/user/_dXDniXt3Xu0U5lkXYliBBHGQRD2FtCUnVVbXPhY'],
  ['台中市', 'Funbox 台中lalaport', 'https://linevoom.line.me/user/_dWbmVBOBVpcGPA3UWP953LsGWVx32VkrDcGrqRQ'],
  ['苗栗縣', 'Funbox Toys-苗栗尚順店', 'https://linevoom.line.me/user/_dVHyXrJlEjwLilMjmYrRy8BYKPofyQgAgsWd8Xk'],
  ['桃園市', 'Funbox-桃園遠東店', 'https://linevoom.line.me/user/_dZCpDMgUi2_f6JEnQze2nP22nJV-G1o8rHLmpFE'],
  ['宜蘭縣', 'Funbox 宜蘭新月店', 'https://linevoom.line.me/user/_dTS4fzrnBtUOuG-T_J22hfcZSdxunoOsypVfgRg'],
  ['高雄市', 'Funbox-夢時代店', 'https://linevoom.line.me/user/_dVHpcOhwVrBQ3ZY1xQBHuGMcluZ-yMcOSsSnRfU'],
  ['台北市', 'Funbox 遠百信義A13', 'https://linevoom.line.me/user/_dZWTe6za3_22gXVkl46uAq37zC6nwkQQCwZnBoA'],
  ['新竹縣', 'funbox 享平方店', 'https://linevoom.line.me/user/_dfuDiJPQBJn4ih1iarevDIEIB9XvR-_q44VI6bE'],
  ['新竹縣', 'Funbox 竹北遠東店', 'https://linevoom.line.me/user/_deu1wnG4xXho1I98-nH_PZKQ0gl-iAoehGDIHxA'],
  ['新竹市', 'Funbox 新竹巨城店', 'https://linevoom.line.me/user/_dSYAGjN3DhBtiB8tU2pa3kl5yoRdBG7ucZNUZvo'],
  ['桃園市', 'Funbox toys - 桃園台茂店', 'https://linevoom.line.me/user/_dZrp8IBATlHOFZaobLCYRrXE5m7abD4dD2ItWm8'],
  ['桃園市', 'Funbox 中壢大江店', 'https://linevoom.line.me/user/_daOwg6Nz08TwGFzWoVR264J1CWj5Lp8g0Lgf-QM'],
  ['桃園市', 'FunBox-中壢SOGO店', 'https://linevoom.line.me/user/_dcSEo3ibPOyoQAAsta4srlSCIdiLnKQqsbk8mog'],
  ['桃園市', 'Funbox Toy-桃園環球A8店', 'https://linevoom.line.me/user/_dWWqORTPgThK__JAqyRDK9PX4ReZqnOFc28vpaE'],
  ['新北市', 'Funbox板橋大遠百', 'https://linevoom.line.me/user/_dblyPGfsKpebVOKvBaP8gs72hysvg-G0EVYLyv4'],
  ['台北市', 'Funbox-南港潤泰', 'https://linevoom.line.me/user/_dSeRV-7dSwPAS21zhFTEZS9TU0cjb1gBLwEML9A'],
  ['台北市', 'Funbox-信義A8店(陀螺販售)', 'https://linevoom.line.me/user/_dfItqTWWpJgcZPNYg_b3_xlBeXDhlwTDTicnfSU'],
  ['台北市', 'Funbox 三越站前店', 'https://linevoom.line.me/user/_dTQ_Ar8kG3TZeWoB_i2PtLW_TclZiMtldppUzAQ'],
  ['台北市', 'Funbox 三越南西店', 'https://linevoom.line.me/user/_dXRCeNI62-wxECClrgjwMfi8HnY2ow5Onw6aC1A'],
  ['台北市', 'Funbox天母三越店', 'https://linevoom.line.me/user/_dXYFKzVX-ldfgeUOor_McfFTE_yJP7d54nPjxpQ'],
  ['新北市', 'Funbox淡水禮萊廣場店', 'https://linevoom.line.me/user/_dU6uuJLZc-sttPrdL6hfb8pOoMDCcgdNWEtYPKA'],
  ['台北市', 'Funbox Toys-大葉高島屋', 'https://linevoom.line.me/user/_dfhvm3-8_klezJkCHLv3-mEhPQWOR9DGFr40SPA'],
  ['新竹市', 'Funbox-新竹遠雄店', 'https://linevoom.line.me/user/_dYdtj10kF6eWUWfcb0xr0dYExX6yYVDk1EksNTU'],
  ['新北市', 'Funbox-中和環球店', 'https://linevoom.line.me/user/_dSg6slLn5Zg47l9CPlGC-LezlX4EP3fmltKvQRs'],
  ['新北市', 'Funbox板橋遠東店', 'https://linevoom.line.me/user/_dUcATZnmDAam7Low6HB0-JXZC1DzUJEbh8hA8Gg'],
  ['台北市', 'Funbox 天母SOGO店', 'https://linevoom.line.me/user/_db3MM1gifrvefmBbBLPWOhPAw0aPUL9K3IvLDTk'],
  ['台南市', 'Funbox Toys-台南南紡店', 'https://linevoom.line.me/user/_dZ41RU2UUbwJMwmDe4O30FG3iEb647ohcj6Txq4'],
  ['台北市', 'Funbox 美麗華', 'https://linevoom.line.me/user/_dS6PecGuAayr8FMQ6NoCcETN1oXZ0zgwun4Uivc'],
  ['新北市', 'FunBox Toys-汐止遠雄店', 'https://linevoom.line.me/user/_dXWlFT8AyCrEdtsk_fRRUYuqERc8rWDzx3c6DUA'],
  ['桃園市', 'FunBox-桃園環球A19店', 'https://linevoom.line.me/user/_dQguBN50HV7T3jjTaZbJKVwoET6cJJH2Kj43Y2E'],
  ['台中市', 'FUNBOX 台中遠百店', 'https://linevoom.line.me/user/_ddG1EBaa4iGasgQdKDdnXo50Y24dW74VXnJuAro'],
  ['台中市', 'Funbox 台中中友店', 'https://linevoom.line.me/user/_dVExgXo7x7ugfZBDIYzfRF8XR9geWiZncXXAkNM'],
  ['桃園市', 'Funbox-桃園站前三越', 'https://linevoom.line.me/user/_dQTwDiZdgoMiaxHmu-STwWJF69wlpmOwL0IjMoY'],
  ['新北市', 'Funbox樹林秀泰店', 'https://linevoom.line.me/user/_dSj7fhnsKdDEm1q2ehrYEJTOyrm4OuI2NFsN3I0'],
  ['新竹市', 'Funbox-新竹遠東店', 'https://linevoom.line.me/user/_dYjgWm0vwMyoPEcmLUOBhOQ55A0WaB7EuLfW5Mw'],
  ['台北市', 'Funbox LaLaport南港', 'https://linevoom.line.me/user/_dVgaAWKsM1ofi6bVa7iJV1_zOspCOrdSv0vgXKw'],
  ['台中市', 'Funbox 廣三SOGO店', 'https://linevoom.line.me/user/_dUpKOzSR_s9Wca-q8vJLgOSM-UGMJNMonlEK_Nw'],
  ['新北市', 'Funbox新店誠品店', 'https://linevoom.line.me/user/_dWQGqQnQTk4Tc7wJjzrBXKS145vBC93TlHkNG5E'],
  ['新北市', 'FUNBOX 比漾廣場店', 'https://linevoom.line.me/user/_dQbxr4jKpXDT3BtXULflBCgU9GujoUvNaAUOOZo']
].map(([region, name, url]) => ({ region, name, url }));
